using OncaPDV.Domain;using OncaPDV.Infrastructure;using Xunit;
namespace OncaPDV.Tests;
public sealed class FinalFeaturesTests:IDisposable
{
 private readonly string _root=Path.Combine(Path.GetTempPath(),"onca-final-"+Guid.NewGuid());private readonly OncaDatabase _db;private readonly FinalFeaturesService _svc;private readonly Guid _op=Guid.NewGuid();
 public FinalFeaturesTests(){Directory.CreateDirectory(_root);var paths=new AppPaths(_root,Path.Combine(_root,"data"),Path.Combine(_root,"backups"),Path.Combine(_root,"logs"),Path.Combine(_root,"exports"),Path.Combine(_root,"print"));_db=new(paths);_db.Migrate();_svc=new(_db);}
 [Fact] public async Task Hold_sale_round_trip_keeps_cart(){var p=Guid.NewGuid();var items=new[]{new CartItem(p,"A","Produto",2,10)};var h=await _svc.HoldAsync("Balcão 2",null,items,0);var all=await _svc.HoldsAsync();Assert.Single(all);Assert.Equal(h.Total,all[0].Total);Assert.Equal(2,all[0].Items[0].Quantity);await _svc.DeleteHoldAsync(h.Id);Assert.Empty(await _svc.HoldsAsync());}
 [Fact] public async Task Expense_requires_open_cash_and_moves_cash(){await OpenCash();var e=await _svc.AddExpenseAsync(_op,25,"Material de uso");Assert.Equal(25,e.Amount);await using var c=_db.Open();await using var q=c.CreateCommand();q.CommandText="SELECT amount FROM cash_movements WHERE origin_id=$id AND type='Expense'";q.Parameters.AddWithValue("$id",e.Id.ToString());Assert.Equal(-25m,Convert.ToDecimal(await q.ExecuteScalarAsync()));}
 [Fact] public async Task History_summary_includes_expenses(){await OpenCash();await _svc.AddExpenseAsync(_op,15,"Água");var s=await _svc.SummaryAsync(DateTimeOffset.Now.AddHours(-1),DateTimeOffset.Now.AddHours(1));Assert.Equal(15,s.Expenses);}
 [Fact] public async Task Return_restores_stock_and_creates_negative_cash_movement(){var setup=await SeedSale();await _svc.ReturnItemAsync(setup.sale,setup.product,1,"Cliente devolveu",_op);await using var c=_db.Open();await using var q=c.CreateCommand();q.CommandText="SELECT stock FROM products WHERE id=$id";q.Parameters.AddWithValue("$id",setup.product.ToString());Assert.Equal(9m,Convert.ToDecimal(await q.ExecuteScalarAsync()));await using var q2=c.CreateCommand();q2.CommandText="SELECT amount FROM cash_movements WHERE origin_id=$sale AND type='Return' ORDER BY rowid DESC LIMIT 1";q2.Parameters.AddWithValue("$sale",setup.sale.ToString());Assert.Equal(-10m,Convert.ToDecimal(await q2.ExecuteScalarAsync()));}
 [Fact] public async Task Exchange_restores_old_deducts_new_and_records_difference(){var setup=await SeedSale();var newp=Guid.NewGuid();await using(var c=_db.Open()){await using var q=c.CreateCommand();q.CommandText="INSERT INTO products(id,internal_code,barcode,name,description,category,brand,cost_price,sale_price,stock,minimum_stock,unit,supplier,photo_path,active) VALUES($id,'N1',NULL,'Novo',NULL,NULL,NULL,5,15,10,0,'UN',NULL,NULL,1)";q.Parameters.AddWithValue("$id",newp.ToString());await q.ExecuteNonQueryAsync();}await _svc.ExchangeItemAsync(setup.sale,setup.product,1,newp,1,"Troca",_op);await using var cc=_db.Open();async Task<decimal> Stock(Guid id){await using var q=cc.CreateCommand();q.CommandText="SELECT stock FROM products WHERE id=$id";q.Parameters.AddWithValue("$id",id.ToString());return Convert.ToDecimal(await q.ExecuteScalarAsync());}Assert.Equal(9m,await Stock(setup.product));Assert.Equal(9m,await Stock(newp));}
 private async Task OpenCash(){await using var c=_db.Open();await using var q=c.CreateCommand();q.CommandText="INSERT INTO cash_sessions VALUES($id,$op,$at,100,NULL,NULL)";q.Parameters.AddWithValue("$id",Guid.NewGuid().ToString());q.Parameters.AddWithValue("$op",_op.ToString());q.Parameters.AddWithValue("$at",DateTimeOffset.Now.ToString("O"));await q.ExecuteNonQueryAsync();}
 private async Task<(Guid sale,Guid product)> SeedSale(){await OpenCash();var product=Guid.NewGuid();var sale=Guid.NewGuid();await using var c=_db.Open();Guid session;await using(var s=c.CreateCommand()){s.CommandText="SELECT id FROM cash_sessions WHERE operator_id=$op AND closed_at IS NULL LIMIT 1";s.Parameters.AddWithValue("$op",_op.ToString());session=Guid.Parse(Convert.ToString(await s.ExecuteScalarAsync())!);}await using var tx=await c.BeginTransactionAsync();async Task E(string sql,params (string,object)[] p){await using var q=c.CreateCommand();q.Transaction=(Microsoft.Data.Sqlite.SqliteTransaction)tx;q.CommandText=sql;foreach(var x in p)q.Parameters.AddWithValue(x.Item1,x.Item2 is Guid g?g.ToString():x.Item2);await q.ExecuteNonQueryAsync();}await E("INSERT INTO products(id,internal_code,barcode,name,description,category,brand,cost_price,sale_price,stock,minimum_stock,unit,supplier,photo_path,active) VALUES($id,'P1',NULL,'Produto',NULL,NULL,NULL,5,10,8,0,'UN',NULL,NULL,1)",( "$id",product));await E("INSERT INTO sales(id,number,created_at,operator_id,customer_id,cash_session_id,discount,total,status,fiscal_status) VALUES($id,1,$at,$op,NULL,$session,0,20,'Completed','NotRequested')",("$id",sale),("$at",DateTimeOffset.Now.ToString("O")),("$op",_op),("$session",session));await E("INSERT INTO sale_items VALUES($id,$sale,$product,'P1','Produto',2,10,20)",( "$id",Guid.NewGuid()),("$sale",sale),("$product",product));await E("INSERT INTO payments VALUES($id,$sale,'Cash',20,20,0)",( "$id",Guid.NewGuid()),("$sale",sale));await E("INSERT INTO cash_movements VALUES($id,$session,'Sale',20,$sale,'Cash',$at)",( "$id",Guid.NewGuid()),("$session",session),("$sale",sale),("$at",DateTimeOffset.Now.ToString("O")));await tx.CommitAsync();return(sale,product);}
 public void Dispose(){Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools();try{Directory.Delete(_root,true);}catch{}}
}

