using OncaPDV.Domain;using OncaPDV.Printing;
namespace OncaPDV.Tests;
public sealed class PrintingIsolationTests
{
 private static readonly ReceiptDocument TestDocument=new(null,"ONCA",OpenDrawer:false,Cut:false,DiagnosticLines:["ONCA","TESTE DE IMPRESSAO","IMPRESSORA OK"]);
 [Fact]public void AsciiTestReceipt_IsExactAndHasOnlyRequiredCommands(){var r=new EscPos80Renderer(CodePagePrinterEncoding.Cp850()).Render(TestDocument);Assert.Equal("ONCA\nTESTE DE IMPRESSAO\nIMPRESSORA OK\n",r.Text);Assert.True(r.Bytes.Take(2).SequenceEqual(new byte[]{0x1B,0x40}));Assert.Contains((byte)0x0A,r.Bytes);Assert.False(Contains(r.Bytes,[0x1D,0x56]));Assert.False(Contains(r.Bytes,[0x1B,0x70]));Assert.Equal(r.Text,System.Text.Encoding.ASCII.GetString(r.Bytes.Skip(2).Take(r.Text.Length).ToArray()));}
 [Theory][InlineData(850)][InlineData(858)][InlineData(860)]public void ConfigurableCodePages_AreAvailable(int codePage){var encoding=new CodePagePrinterEncoding(codePage);Assert.NotEmpty(encoding.GetBytes("ONCA"));}
 [Fact]public async Task PhysicalFalse_BlocksOnlinePrinterBeforeEveryApi(){using var temp=new Temp();var transport=new CountingTransport(PrinterAvailability.Online);var result=await new WindowsRawPrintService(new EscPos80Renderer(),temp.Path,false,transport).PrintAsync(TestDocument,"POS-80");Assert.False(result.Success);Assert.Equal("Impressão física bloqueada por configuração.",result.Error);Assert.Equal(0,transport.PhysicalApiCalls);Assert.Equal(0,transport.AvailabilityChecks);}
 [Fact]public async Task OfflinePrinter_SendsNothing(){using var temp=new Temp();var transport=new CountingTransport(PrinterAvailability.Offline);var result=await new WindowsRawPrintService(new EscPos80Renderer(),temp.Path,true,transport).PrintAsync(TestDocument,"POS-80");Assert.False(result.Success);Assert.Contains("IMPRESSORA OFFLINE",result.Error);Assert.Equal(0,transport.PhysicalApiCalls);Assert.Equal(1,transport.AvailabilityChecks);}
 [Fact]public async Task EmptyReceipt_IsBlockedBeforeSpooler(){using var temp=new Temp();var transport=new CountingTransport(PrinterAvailability.Online);var empty=new ReceiptDocument(new Sale(Guid.NewGuid(),1,DateTimeOffset.Now,Guid.NewGuid(),null,[],[],0,0));var ex=await Assert.ThrowsAsync<InvalidOperationException>(()=>new WindowsRawPrintService(new EscPos80Renderer(),temp.Path,true,transport).PrintAsync(empty,"POS-80"));Assert.Equal("PRINT BLOCKED - EMPTY RECEIPT",ex.Message);Assert.Equal(0,transport.PhysicalApiCalls);}
 [Fact]public async Task FailingRenderer_CancelsBeforeSpooler(){using var temp=new Temp();var transport=new CountingTransport(PrinterAvailability.Online);await Assert.ThrowsAsync<InvalidDataException>(()=>new WindowsRawPrintService(new FailingRenderer(),temp.Path,true,transport).PrintAsync(TestDocument,"POS-80"));Assert.Equal(0,transport.PhysicalApiCalls);Assert.Equal(0,transport.AvailabilityChecks);}
 [Fact]public async Task ThousandMockPrints_CompleteWithoutPhysicalCallsOrQueueCorruption(){using var temp=new Temp();var transport=new CountingTransport(PrinterAvailability.Online);var mock=new MockPrintService(new EscPos80Renderer(),temp.Path);var rendered=0;for(var i=0;i<1000;i++){var result=await mock.PrintAsync(TestDocument);Assert.True(result.Success);rendered++;}Assert.Equal(1000,rendered);Assert.Equal(1000,Directory.GetFiles(temp.Path,"*.bin").Length);Assert.Equal(1000,Directory.GetFiles(temp.Path,"*.txt").Length);Assert.Equal(0,transport.PhysicalApiCalls);}
 private static bool Contains(byte[] source,byte[] value)=>source.AsSpan().IndexOf(value)>=0;
 private sealed class CountingTransport(PrinterAvailability availability):IPhysicalPrinterTransport{public int AvailabilityChecks{get;private set;}public int OpenPrinterCalls{get;private set;}public int StartDocPrinterCalls{get;private set;}public int StartPagePrinterCalls{get;private set;}public int WritePrinterCalls{get;private set;}public int PhysicalApiCalls=>OpenPrinterCalls+StartDocPrinterCalls+StartPagePrinterCalls+WritePrinterCalls;public PrinterAvailability GetAvailability(string printerName){AvailabilityChecks++;return availability;}public SpoolerTrace Send(string printerName,byte[] bytes){OpenPrinterCalls++;StartDocPrinterCalls++;StartPagePrinterCalls++;WritePrinterCalls++;return new(true,true,true,true,true,true,bytes.Length,bytes.Length,0);}}
 private sealed class FailingRenderer:IReceiptRenderer{public RenderedReceipt Render(ReceiptDocument document)=>throw new InvalidDataException("Renderer inválido.");}
 private sealed class Temp:IDisposable{public string Path{get;}=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"onca-print-isolation-"+Guid.NewGuid());public Temp()=>Directory.CreateDirectory(Path);public void Dispose(){if(Directory.Exists(Path))Directory.Delete(Path,true);}}
}
