using Microsoft.Data.Sqlite;using OncaPDV.Application;using OncaPDV.Domain;
namespace OncaPDV.Infrastructure;
public sealed class SqliteCustomerRepository(OncaDatabase db):ICustomerRepository
{
 public async Task SaveAsync(CustomerProfile x,CancellationToken ct=default){if(!BrazilianTaxId.IsValid(x.Cpf)||!BrazilianTaxId.IsValid(x.Cnpj))throw new DomainException("CPF/CNPJ inválido.");await using var c=db.Open();await using var q=c.CreateCommand();q.CommandText="INSERT INTO customers(id,name,cpf,cnpj,phone,whatsapp,email,postal_code,address,number,complement,district,city,state,notes,active) VALUES($id,$name,$cpf,$cnpj,$phone,$wa,$email,$cep,$address,$number,$complement,$district,$city,$state,$notes,$active) ON CONFLICT(id) DO UPDATE SET name=excluded.name,cpf=excluded.cpf,cnpj=excluded.cnpj,phone=excluded.phone,whatsapp=excluded.whatsapp,email=excluded.email,postal_code=excluded.postal_code,address=excluded.address,number=excluded.number,complement=excluded.complement,district=excluded.district,city=excluded.city,state=excluded.state,notes=excluded.notes,active=excluded.active";Add(q,x);try{await q.ExecuteNonQueryAsync(ct);}catch(SqliteException ex)when(ex.SqliteErrorCode==19){throw new DuplicateCustomerException("CPF ou CNPJ já cadastrado.");}}
 public async Task<IReadOnlyList<CustomerProfile>> SearchAsync(string term,bool includeInactive=false,CancellationToken ct=default){var list=new List<CustomerProfile>();await using var c=db.Open();await using var q=c.CreateCommand();q.CommandText="SELECT * FROM customers WHERE ($all=1 OR active=1) AND (name LIKE $q OR phone LIKE $q OR cpf LIKE $q OR cnpj LIKE $q) ORDER BY name LIMIT 100";q.Parameters.AddWithValue("$all",includeInactive?1:0);q.Parameters.AddWithValue("$q",$"%{term}%");await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(Read(r));return list;}
 public async Task<CustomerProfile?> GetAsync(Guid id,CancellationToken ct=default){await using var c=db.Open();await using var q=c.CreateCommand();q.CommandText="SELECT * FROM customers WHERE id=$id";q.Parameters.AddWithValue("$id",id.ToString());await using var r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?Read(r):null;}
 private static void Add(SqliteCommand q,CustomerProfile x){var values=new Dictionary<string,object?>{{"$id",x.Id.ToString()},{"$name",x.Name},{"$cpf",x.Cpf},{"$cnpj",x.Cnpj},{"$phone",x.Phone},{"$wa",x.WhatsApp},{"$email",x.Email},{"$cep",x.PostalCode},{"$address",x.Address},{"$number",x.Number},{"$complement",x.Complement},{"$district",x.District},{"$city",x.City},{"$state",x.State},{"$notes",x.Notes},{"$active",x.Active?1:0}};foreach(var p in values)q.Parameters.AddWithValue(p.Key,p.Value??DBNull.Value);}
 private static CustomerProfile Read(SqliteDataReader r){string? T(string n){var i=r.GetOrdinal(n);return r.IsDBNull(i)?null:r.GetString(i);}return new(Guid.Parse(T("id")!),T("name")!,T("cpf"),T("cnpj"),T("phone"),T("whatsapp"),T("email"),T("postal_code"),T("address"),T("number"),T("complement"),T("district"),T("city"),T("state"),T("notes"),r.GetInt32(r.GetOrdinal("active"))==1);}
}
public sealed class SqliteCreditRepository(OncaDatabase db,IClock clock):ICreditRepository
{
 public async Task<IReadOnlyList<CreditAccount>> ByCustomerAsync(Guid customerId,CancellationToken ct=default){var list=new List<CreditAccount>();await using var c=db.Open();await using var q=c.CreateCommand();q.CommandText="SELECT * FROM credit_accounts WHERE customer_id=$id ORDER BY due_at";q.Parameters.AddWithValue("$id",customerId.ToString());await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(Read(r));return list;}
 public async Task<CreditReceipt> ReceiveAsync(Guid accountId,decimal amount,PaymentMethod method,Guid operatorId,Guid sessionId,string? notes,CancellationToken ct=default){if(amount<=0)throw new DomainException("Valor inválido.");await using var c=db.Open();await using var tx=await c.BeginTransactionAsync(ct);decimal balance;await using(var get=c.CreateCommand()){get.Transaction=(SqliteTransaction)tx;get.CommandText="SELECT balance FROM credit_accounts WHERE id=$id AND status NOT IN ('Paid','Cancelled')";get.Parameters.AddWithValue("$id",accountId.ToString());var v=await get.ExecuteScalarAsync(ct);if(v is null)throw new DomainException("Conta não encontrada ou encerrada.");balance=Convert.ToDecimal(v);}if(amount>balance)throw new DomainException("Recebimento maior que o saldo.");var receipt=new CreditReceipt(Guid.NewGuid(),accountId,amount,method,operatorId,clock.Now,notes);await Exec(c,(SqliteTransaction)tx,"INSERT INTO credit_receipts VALUES($id,$account,$amount,$method,$op,$at,$notes)",( "$id",receipt.Id),("$account",accountId),("$amount",amount),("$method",method.ToString()),("$op",operatorId),("$at",receipt.CreatedAt.ToString("O")),("$notes",(object?)notes??DBNull.Value));await Exec(c,(SqliteTransaction)tx,"UPDATE credit_accounts SET balance=balance-$amount,status=CASE WHEN balance-$amount=0 THEN 'Paid' ELSE 'Partial' END WHERE id=$id",("$amount",amount),("$id",accountId));await Exec(c,(SqliteTransaction)tx,"INSERT INTO cash_movements VALUES($id,$session,'StoreCreditReceipt',$amount,$account,'RECEBIMENTO CREDIÁRIO',$at)",( "$id",Guid.NewGuid()),("$session",sessionId),("$amount",amount),("$account",accountId),("$at",receipt.CreatedAt.ToString("O")));await tx.CommitAsync(ct);return receipt;}
 private static async Task Exec(SqliteConnection c,SqliteTransaction tx,string sql,params(string,object)[] ps){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText=sql;foreach(var p in ps)q.Parameters.AddWithValue(p.Item1,p.Item2 is Guid id?id.ToString():p.Item2);await q.ExecuteNonQueryAsync();}
 private static CreditAccount Read(SqliteDataReader r)=>new(Guid.Parse(r.GetString(r.GetOrdinal("id"))),Guid.Parse(r.GetString(r.GetOrdinal("customer_id"))),Guid.Parse(r.GetString(r.GetOrdinal("sale_id"))),r.GetDecimal(r.GetOrdinal("original_amount")),r.GetDecimal(r.GetOrdinal("balance")),DateTimeOffset.Parse(r.GetString(r.GetOrdinal("created_at"))),DateTimeOffset.Parse(r.GetString(r.GetOrdinal("due_at"))),Enum.Parse<CreditStatus>(r.GetString(r.GetOrdinal("status"))),r.GetInt32(r.GetOrdinal("installments")),r.IsDBNull(r.GetOrdinal("notes"))?null:r.GetString(r.GetOrdinal("notes")));
}
