<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.1" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.13" />
    <ProjectReference Include="..\OncaPDV.Domain\OncaPDV.Domain.csproj" />
    <ProjectReference Include="..\OncaPDV.Application\OncaPDV.Application.csproj" />
    <ProjectReference Include="..\OncaPDV.Printing\OncaPDV.Printing.csproj" />
  </ItemGroup>

</Project>
