using Microsoft.Data.Sqlite;using OncaPDV.Application;using OncaPDV.Domain;using OncaPDV.Infrastructure;
namespace OncaPDV.Tests;
public sealed class BusinessModuleTests
{
 [Fact]public async Task CustomerWithoutTaxId_IsAllowed(){using var e=new Env();var r=new SqliteCustomerRepository(e.Db);var x=Customer();await r.SaveAsync(x);Assert.Equal(x.Id,(await r.SearchAsync("Maria")).Single().Id);}
 [Theory][InlineData("52998224725",true)][InlineData("52998224724",false)][InlineData("11222333000181",true)][InlineData("11222333000182",false)]public void TaxIdValidation(string id,bool expected)=>Assert.Equal(expected,BrazilianTaxId.IsValid(id));
 [Fact]public async Task DuplicateCpf_IsFriendly(){using var e=new Env();var r=new SqliteCustomerRepository(e.Db);await r.SaveAsync(Customer(cpf:"52998224725"));await Assert.ThrowsAsync<DuplicateCustomerException>(()=>r.SaveAsync(Customer(cpf:"52998224725")));}
 [Fact]public async Task MixedPayment_WithCashChange_IsAtomic(){using var e=new Env();var product=new Product(Guid.NewGuid(),"MIX","900", "Produto",null,null,null,1,10,20,0,"UN",null,null,true);var products=new SqliteProductRepository(e.Db);await products.SaveAsync(product);var sales=new SqliteSaleRepository(e.Db,new SystemClock());var cart=new Cart();cart.Add(product,10);var op=Guid.NewGuid();var session=await new SqliteCashSessionRepository(e.Db,new SystemClock()).GetOrOpenAsync(op);var payments=new[]{new Payment(PaymentMethod.Pix,30),new Payment(PaymentMethod.Cash,70,120)};var sale=await new CheckoutService(sales,new JsonCartRecoveryStore(e.Paths)).CompleteAsync(cart,payments,op,session.Id);Assert.Equal(100,sale.Total);Assert.Equal(50,payments[1].Change);Assert.Equal(2,await e.Count("payments"));Assert.Equal(2,await e.Count("cash_movements"));Assert.Equal(10,await e.Decimal("SELECT stock FROM products WHERE id=$id",("$id",product.Id)));}
 [Fact]public async Task StoreCreditAndPartialThenTotalReceipt_AreAuditable(){using var e=new Env();var customer=Customer();await new SqliteCustomerRepository(e.Db).SaveAsync(customer);var product=new Product(Guid.NewGuid(),"CR","901","Produto",null,null,null,1,100,2,0,"UN",null,null,true);await new SqliteProductRepository(e.Db).SaveAsync(product);var op=Guid.NewGuid();var cash=new SqliteCashSessionRepository(e.Db,new SystemClock());var session=await cash.GetOrOpenAsync(op);var cart=new Cart{CustomerId=customer.Id};cart.Add(product);await new CheckoutService(new SqliteSaleRepository(e.Db,new SystemClock()),new JsonCartRecoveryStore(e.Paths)).CompleteAsync(cart,[new(PaymentMethod.StoreCredit,100)],op,session.Id);var repo=new SqliteCreditRepository(e.Db,new SystemClock());var account=(await repo.ByCustomerAsync(customer.Id)).Single();Assert.Equal(100,account.Balance);await repo.ReceiveAsync(account.Id,40,PaymentMethod.Pix,op,session.Id,null);account=(await repo.ByCustomerAsync(customer.Id)).Single();Assert.Equal(60,account.Balance);Assert.Equal(CreditStatus.Partial,account.Status);await repo.ReceiveAsync(account.Id,60,PaymentMethod.Cash,op,session.Id,null);account=(await repo.ByCustomerAsync(customer.Id)).Single();Assert.Equal(0,account.Balance);Assert.Equal(CreditStatus.Paid,account.Status);Assert.Equal(2,await e.Count("credit_receipts"));Assert.Equal(2,await e.Count("cash_movements"));Assert.Equal(1,await e.Count("sales"));}
 [Fact]public async Task Supplier_can_be_saved_and_searched(){using var e=new Env();var service=new SupplierService(e.Db);var supplier=new Supplier(Guid.NewGuid(),"Fornecedor Teste","11222333000181","1199999999",null);await service.SaveAsync(supplier);Assert.Equal(supplier.Id,(await service.SearchAsync("112223")).Single().Id);Assert.Equal(4,await e.Decimal("SELECT MAX(version) FROM schema_versions"));}
 [Fact]public async Task Purchase_atomically_updates_cost_stock_and_movement(){using var e=new Env();var supplier=new Supplier(Guid.NewGuid(),"Fornecedor",null,null,null);await new SupplierService(e.Db).SaveAsync(supplier);var product=new Product(Guid.NewGuid(),"COMPRA","902","Produto",null,null,null,2,10,5,0,"UN",null,null,true);await new SqliteProductRepository(e.Db).SaveAsync(product);var purchase=await new PurchaseService(e.Db).CompleteAsync(supplier.Id,[new(product.Id,product.InternalCode,product.Name,3,4)],"NF-1");Assert.Equal(12,purchase.Total);Assert.Equal(8,await e.Decimal("SELECT stock FROM products WHERE id=$id",("$id",product.Id)));Assert.Equal(4,await e.Decimal("SELECT cost_price FROM products WHERE id=$id",("$id",product.Id)));Assert.Equal(1,await e.Count("purchases"));Assert.Equal(1,await e.Count("purchase_items"));Assert.Equal(1,await e.Decimal("SELECT COUNT(*) FROM stock_movements WHERE origin_id=$id AND type='Purchase'",("$id",purchase.Id)));}
 [Fact]public async Task Printer_profile_is_independent_per_terminal_and_keeps_physical_disabled(){using var e=new Env();var store=new TerminalPrinterProfileStore(e.Paths);await store.SaveAsync(new("CAIXA-01","POS-80","USB001",80,OncaPDV.Printing.PrintBackend.EscPosRaw,"CP850",false,false));await store.SaveAsync(new("CAIXA-02","Outra","USB002",58,OncaPDV.Printing.PrintBackend.WindowsDriver,"CP860",false,false));var one=await store.LoadAsync("CAIXA-01");var two=await store.LoadAsync("CAIXA-02");Assert.Equal("POS-80",one!.PrinterName);Assert.Equal(80,one.PaperWidthMm);Assert.Equal("Outra",two!.PrinterName);Assert.Equal(58,two.PaperWidthMm);Assert.False(one.CutEnabled);Assert.False(two.DrawerEnabled);}
 private static CustomerProfile Customer(string? cpf=null)=>new(Guid.NewGuid(),"Maria",cpf,null,"11999999999",null,null,null,null,null,null,null,null,null,null,true);
 private sealed class Env:IDisposable{public string Root{get;}=Path.Combine(Path.GetTempPath(),"onca-business-"+Guid.NewGuid());public AppPaths Paths{get;}public OncaDatabase Db{get;}public Env(){Paths=new(Root,Path.Combine(Root,"data"),Path.Combine(Root,"backup"),Path.Combine(Root,"logs"),Path.Combine(Root,"exports"),Path.Combine(Root,"print"));Db=new(Paths);Db.Migrate();}public async Task<long> Count(string table)=>Convert.ToInt64(await Scalar($"SELECT COUNT(*) FROM {table}"));public async Task<decimal> Decimal(string sql,params(string,object)[] ps)=>Convert.ToDecimal(await Scalar(sql,ps));private async Task<object?> Scalar(string sql,params(string,object)[] ps){await using var c=Db.Open();await using var q=c.CreateCommand();q.CommandText=sql;foreach(var p in ps)q.Parameters.AddWithValue(p.Item1,p.Item2 is Guid id?id.ToString():p.Item2);return await q.ExecuteScalarAsync();}public void Dispose(){SqliteConnection.ClearAllPools();if(Directory.Exists(Root))Directory.Delete(Root,true);}}
}
