using Microsoft.Data.Sqlite;
using OncaPDV.Application;
using OncaPDV.Domain;
using OncaPDV.Fiscal;
using OncaPDV.Infrastructure;
using OncaPDV.Migration;
using OncaPDV.Printing;

namespace OncaPDV.Tests;

public class CoreTests
{
    private static Product Product(decimal stock=20,string code="P1",string? barcode="7891",string name="Detergente")=>new(Guid.NewGuid(),code,barcode,name,null,"Limpeza","ONÇA",2,5,stock,2,"UN",null,null,true);
    [Fact] public void Cart_CalculatesQuantityDiscountAndTotal(){var c=new Cart();var p=Product();c.Add(p);c.ChangeQuantity(p.Id,3);c.SetDiscount(2);Assert.Equal(13,c.Total);}
    [Fact] public void Cash_CalculatesChange(){Assert.Equal(5,new Payment(PaymentMethod.Cash,15,20).Change);}
    [Fact] public void Password_IsSaltedAndVerified(){var a=PasswordHasher.Hash("1234");var b=PasswordHasher.Hash("1234");Assert.NotEqual(a,b);Assert.True(PasswordHasher.Verify("1234",a));Assert.False(PasswordHasher.Verify("0000",a));}
    [Fact] public void Scanner_BlocksOnlyImmediateDuplicate(){var clock=new FakeClock();var guard=new ScannerDuplicateGuard(clock,TimeSpan.FromMilliseconds(500));Assert.True(guard.Accept("789"));Assert.False(guard.Accept("789"));clock.Now+=TimeSpan.FromSeconds(1);Assert.True(guard.Accept("789"));}
    [Theory][InlineData(true)][InlineData(false)] public void EscPos_HasInitFeedAndOptionalCut(bool cut){var sale=SaleWithItems(1);var r=new EscPos58Renderer().Render(new(sale,Cut:cut));Assert.True(r.Bytes.Length>ReceiptValidator.MinimumBytes);Assert.Equal(0x1B,r.Bytes[0]);Assert.Equal(cut,r.Bytes.TakeLast(3).SequenceEqual(new byte[]{0x1D,0x56,0x01}));}
    [Fact] public void EmptyReceipt_IsBlocked(){var sale=SaleWithItems(0);Assert.Throws<InvalidOperationException>(()=>new EscPos80Renderer().Render(new(sale)));}
    [Fact] public async Task ControlledPhysicalTest_MockPassesAndHardwareRemainsBlocked(){using var env=TestEnv.Create();IReceiptRenderer renderer=new EscPos80Renderer();var doc=new ReceiptDocument(null,"ONÇA",Cut:false,DiagnosticLines:["ONÇA","TESTE DE IMPRESSÃO","IMPRESSORA OK"]);var rendered=renderer.Render(doc);Assert.Contains("ONÇA",rendered.Text);Assert.Contains("IMPRESSORA OK",rendered.Text);Assert.True(rendered.Bytes.Take(2).SequenceEqual(new byte[]{0x1B,0x40}));Assert.Contains((byte)0x0A,rendered.Bytes);Assert.False(rendered.Bytes.TakeLast(3).SequenceEqual(new byte[]{0x1D,0x56,0x01}));var mock=await new MockPrintService(renderer,env.Paths.PrintPreview).PrintAsync(doc);Assert.True(mock.Success);var blocked=await new WindowsRawPrintService(renderer,env.Paths.Logs,false).PrintAsync(doc,"POS-80");Assert.False(blocked.Success);Assert.Null(blocked.Trace);Assert.True(File.Exists(Path.Combine(env.Paths.Logs,"print-last.txt")));Assert.True(File.Exists(Path.Combine(env.Paths.Logs,"print-last-escpos.bin")));}
    [Fact] public async Task Mock_Prints100WithoutHardware(){var dir=Path.Combine(Path.GetTempPath(),"onca-print-"+Guid.NewGuid());var service=new MockPrintService(new MockReceiptRenderer(),dir);for(var i=0;i<100;i++)Assert.True((await service.PrintAsync(new(SaleWithItems(10) with {Number=i+1}))).Success);Assert.Equal(100,Directory.GetFiles(dir,"*.bin").Length);Directory.Delete(dir,true);}
    [Fact] public async Task Recovery_RestoresCart(){var env=TestEnv.Create();var c=new Cart();c.Add(Product(),2);c.SetDiscount(1);var store=new JsonCartRecoveryStore(env.Paths);await store.SaveAsync(c);var restored=await store.LoadAsync();Assert.NotNull(restored);Assert.Single(restored.Items);Assert.Equal(9,restored.Total);env.Dispose();}
    [Fact] public async Task DuplicateCodes_AreRejectedByDatabase(){var env=TestEnv.Create();var repo=new SqliteProductRepository(env.Db);await repo.SaveAsync(Product(code:"X",barcode:"B"));await Assert.ThrowsAsync<DuplicateProductException>(()=>repo.SaveAsync(Product(code:"X",barcode:"C")));await Assert.ThrowsAsync<DuplicateProductException>(()=>repo.SaveAsync(Product(code:"Y",barcode:"B")));env.Dispose();}
    [Fact] public async Task EqualProductNamesAreAllowedAndExactCodeRanksFirst(){using var env=TestEnv.Create();var repo=new SqliteProductRepository(env.Db);var a=Product(code:"DET-A",barcode:"1001",name:"Detergente Neutro");var b=Product(code:"DET-B",barcode:"1002",name:"Detergente Neutro");await repo.SaveAsync(a);await repo.SaveAsync(b);var results=await repo.SearchAsync("Detergente Neutro");Assert.Equal(2,results.Count);Assert.Equal(a.Id,(await repo.SearchAsync("DET-A")).First().Id);}
    [Fact] public async Task ProductEditPreservesStockAndIdentity(){using var env=TestEnv.Create();var repo=new SqliteProductRepository(env.Db);var original=Product(stock:17,code:"safe-1",barcode:"2001");await repo.SaveAsync(original);await repo.SaveAsync(original with{Name="Nome editado",SalePrice=9,Stock=999});var saved=await repo.FindAsync("SAFE-1");Assert.Equal(original.Id,saved!.Id);Assert.Equal("Nome editado",saved.Name);Assert.Equal(17,saved.Stock);Assert.Equal(9,saved.SalePrice);}
    [Fact] public async Task QuickProductCreationPreservesExistingCart(){using var env=TestEnv.Create();var repo=new SqliteProductRepository(env.Db);var workflow=new PosWorkflow(repo,new JsonCartRecoveryStore(env.Paths),new SqliteSaleRepository(env.Db,new SystemClock()),new SqliteCashSessionRepository(env.Db,new SystemClock()),new SystemClock());var first=Product(code:"CART-1",barcode:"3001");await workflow.AddProductAsync(first,true);var second=Product(code:"CART-2",barcode:"3002",name:"Produto novo");await workflow.AddProductAsync(second,true);Assert.Equal(2,workflow.Cart.Items.Count);Assert.Contains(workflow.Cart.Items,x=>x.ProductId==first.Id);Assert.Contains(workflow.Cart.Items,x=>x.ProductId==second.Id);}
    [Fact] public async Task ProductSurvivesValidatedBackupRestore(){using var env=TestEnv.Create();var repo=new SqliteProductRepository(env.Db);var product=Product(stock:23,code:"BACK-P",barcode:"4001",name:"Produto preservado");await repo.SaveAsync(product);var ops=new OperationalService(env.Db,env.Paths);var backup=await ops.CreateBackupAsync();await repo.SaveAsync(product with{Name="Alterado depois",Stock=500});await ops.RestoreAsync(backup);var restored=await repo.FindAsync("BACK-P");Assert.NotNull(restored);Assert.Equal(product.Id,restored!.Id);Assert.Equal("Produto preservado",restored.Name);Assert.Equal(23,restored.Stock);Assert.Equal("ok",env.Db.IntegrityCheck());}
    [Fact] public async Task LegacyProductDryRunIsReadOnlyAndReportsConflicts(){var root=Path.Combine(Path.GetTempPath(),"onca-legacy-dry-"+Guid.NewGuid());Directory.CreateDirectory(root);var file=Path.Combine(root,"legacy.db");try{await using(var c=new SqliteConnection($"Data Source={file}")){await c.OpenAsync();await using var q=c.CreateCommand();q.CommandText="CREATE TABLE produtos(codigo TEXT,codigo_barras TEXT,nome TEXT);INSERT INTO produtos VALUES('A','1','Mesmo nome'),('A','2','Mesmo nome'),('B','2','Outro'),(NULL,NULL,'Sem código')";await q.ExecuteNonQueryAsync();}var report=await new LegacyAnalyzer().AnalyzeProductsDryRunAsync(file);Assert.False(report.ImportExecuted);Assert.Equal(report.SourceSha256Before,report.SourceSha256After);Assert.Equal(4,report.Rows);Assert.Equal(1,report.MissingInternalCode);Assert.Equal(1,report.DuplicateInternalCodes);Assert.Equal(1,report.DuplicateBarcodes);Assert.Equal(1,report.DuplicateNames);}finally{SqliteConnection.ClearAllPools();Directory.Delete(root,true);}}
    [Fact] public async Task Sale_IsAtomicAndMovesStockCashAndPayments(){var env=TestEnv.Create();var repo=new SqliteProductRepository(env.Db);var p=Product();await repo.SaveAsync(p);var operatorId=Guid.NewGuid();var session=Guid.NewGuid();await env.Sql("INSERT INTO cash_sessions(id,operator_id,opened_at,opening_amount) VALUES($id,$op,$at,100)",( "$id",session),("$op",operatorId),("$at",DateTimeOffset.Now.ToString("O")));var cart=new Cart();cart.Add(p,2);var sale=await new SqliteSaleRepository(env.Db,new SystemClock()).CompleteAsync(cart,[new(PaymentMethod.Pix,10)],operatorId,session);Assert.Equal(1,await env.Count("sales"));Assert.Equal(1,await env.Count("sale_items"));Assert.Equal(1,await env.Count("payments"));Assert.Equal(2,await env.Count("stock_movements"));Assert.Equal(1,await env.Count("cash_movements"));Assert.Equal(18,await env.ScalarDecimal("SELECT stock FROM products WHERE id=$id",("$id",p.Id)));env.Dispose();}
    [Fact] public async Task InsufficientStock_RollsEverythingBack(){var env=TestEnv.Create();var repo=new SqliteProductRepository(env.Db);var p=Product(stock:1);await repo.SaveAsync(p);var op=Guid.NewGuid();var session=Guid.NewGuid();await env.Sql("INSERT INTO cash_sessions(id,operator_id,opened_at,opening_amount) VALUES($id,$op,$at,0)",( "$id",session),("$op",op),("$at",DateTimeOffset.Now.ToString("O")));var cart=new Cart();cart.Add(p,2);await Assert.ThrowsAsync<DomainException>(()=>new SqliteSaleRepository(env.Db,new SystemClock()).CompleteAsync(cart,[new(PaymentMethod.Cash,10,10)],op,session));Assert.Equal(0,await env.Count("sales"));Assert.Equal(1,await env.ScalarDecimal("SELECT stock FROM products WHERE id=$id",("$id",p.Id)));env.Dispose();}
    [Fact] public async Task Backup_IsValidated(){var env=TestEnv.Create();var file=await new BackupService(env.Db,env.Paths).CreateAsync();Assert.True(File.Exists(file));env.Dispose();}
    [Fact] public async Task FiscalMock_RefusesProductionAndAuthorizesHomologation(){var p=new MockFiscalProvider();Assert.Equal(FiscalStatus.Rejected,(await p.IssueAsync(new(SaleWithItems(1),"65","Producao"))).Status);Assert.Equal(FiscalStatus.Authorized,(await p.IssueAsync(new(SaleWithItems(1),"65","Homologacao"))).Status);}
    [Fact] public async Task EndToEnd_ApplicationFlow_ReprintDoesNotDuplicateSaleOrMovements(){using var env=TestEnv.Create();var products=new SqliteProductRepository(env.Db);var sales=new SqliteSaleRepository(env.Db,new SystemClock());var workflow=new PosWorkflow(products,new JsonCartRecoveryStore(env.Paths),sales,new SqliteCashSessionRepository(env.Db,new SystemClock()),new SystemClock());var product=Product(stock:20,code:"E2E",barcode:"7890001");await workflow.AddProductAsync(product,false);Assert.Equal(ScanStatus.Added,(await workflow.ScanAsync("7890001")).Status);await workflow.ChangeQuantityAsync(product.Id,3);Assert.Equal(15,workflow.Cart.Total);var payment=new Payment(PaymentMethod.Cash,15,20);Assert.Equal(5,payment.Change);var sale=await workflow.CompleteAsync([payment],Guid.NewGuid());var printer=new QueuedPrintService(new MockPrintService(new EscPos80Renderer(),env.Paths.PrintPreview),env.Db);Assert.True((await printer.PrintAsync(new(sale))).Success);var fromHistory=(await workflow.LastSalesAsync()).Single();Assert.Equal(3,fromHistory.Items.Single().Quantity);Assert.True((await printer.PrintAsync(new(fromHistory))).Success);Assert.Equal(1,await env.Count("sales"));Assert.Equal(2,await env.Count("stock_movements"));Assert.Equal(1,await env.Count("cash_movements"));Assert.Equal(2,await env.Count("print_jobs"));Assert.Equal(2,Directory.GetFiles(env.Paths.PrintPreview,"*.bin").Length);Assert.Equal(17,await env.ScalarDecimal("SELECT stock FROM products WHERE id=$id",("$id",product.Id)));}
    [Fact] public async Task CancelledRecoveredCart_DoesNotReturn(){using var env=TestEnv.Create();var repo=new SqliteProductRepository(env.Db);var store=new JsonCartRecoveryStore(env.Paths);var sales=new SqliteSaleRepository(env.Db,new SystemClock());var cash=new SqliteCashSessionRepository(env.Db,new SystemClock());var p=Product();await repo.SaveAsync(p);var first=new PosWorkflow(repo,store,sales,cash,new SystemClock());await first.ScanAsync(p.Barcode!);var reopened=new PosWorkflow(repo,store,sales,cash,new SystemClock());Assert.True(await reopened.InitializeAsync());Assert.Single(reopened.Cart.Items);await reopened.CancelAsync();var afterCancel=new PosWorkflow(repo,store,sales,cash,new SystemClock());Assert.False(await afterCancel.InitializeAsync());Assert.Empty(afterCancel.Cart.Items);}
    [Fact] public async Task DatabasePragmas_AreSafe(){using var env=TestEnv.Create();Assert.Equal("ok",env.Db.IntegrityCheck());Assert.Equal(1,Convert.ToInt64(await env.ScalarPublic("PRAGMA foreign_keys")));Assert.Equal("wal",Convert.ToString(await env.ScalarPublic("PRAGMA journal_mode")));}
    [Fact] public async Task SearchAmong1000Products_IsFast(){using var env=TestEnv.Create();var repo=new SqliteProductRepository(env.Db);for(var i=0;i<1000;i++)await repo.SaveAsync(Product(code:$"T{i:0000}",barcode:$"900{i:0000}",name:$"Produto teste {i:0000}"));var sw=System.Diagnostics.Stopwatch.StartNew();var found=await repo.FindAsync("T0999");sw.Stop();Assert.NotNull(found);Assert.True(sw.Elapsed<TimeSpan.FromSeconds(1),$"Busca levou {sw.ElapsedMilliseconds} ms");}
    [Fact] public void CartWith100DifferentItems_CalculatesQuickly(){var cart=new Cart();var sw=System.Diagnostics.Stopwatch.StartNew();for(var i=0;i<100;i++)cart.Add(Product(code:$"C{i}",barcode:$"BC{i}"));var total=cart.Total;sw.Stop();Assert.Equal(500,total);Assert.True(sw.Elapsed<TimeSpan.FromSeconds(1));}
    private static Sale SaleWithItems(int count){var items=Enumerable.Range(1,count).Select(i=>new CartItem(Guid.NewGuid(),$"P{i}",i==1?new string('X',80):$"Produto {i}",1,5)).ToArray();return new(Guid.NewGuid(),1,DateTimeOffset.Now,Guid.NewGuid(),null,items,[new(PaymentMethod.Cash,count*5,count*5+2)],0,count*5);}
    private sealed class FakeClock:IClock{public DateTimeOffset Now{get;set;}=DateTimeOffset.Now;}
    private sealed class TestEnv:IDisposable
    {
        public string Root{get;}=Path.Combine(Path.GetTempPath(),"onca-tests-"+Guid.NewGuid());public AppPaths Paths{get;}public OncaDatabase Db{get;}
        private TestEnv(){Paths=new(Root,Path.Combine(Root,"data"),Path.Combine(Root,"backup"),Path.Combine(Root,"logs"),Path.Combine(Root,"exports"),Path.Combine(Root,"print"));Db=new(Paths);Db.Migrate();}
        public static TestEnv Create()=>new();public async Task<long> Count(string table)=>Convert.ToInt64(await Scalar($"SELECT COUNT(*) FROM {table}"));public async Task<decimal> ScalarDecimal(string sql,params(string,object)[] ps)=>Convert.ToDecimal(await Scalar(sql,ps));
        public Task<object?> ScalarPublic(string sql,params(string,object)[] ps)=>Scalar(sql,ps);private async Task<object?> Scalar(string sql,params(string,object)[] ps){await using var c=Db.Open();await using var q=c.CreateCommand();q.CommandText=sql;foreach(var p in ps)q.Parameters.AddWithValue(p.Item1,p.Item2 is Guid id?id.ToString():p.Item2);return await q.ExecuteScalarAsync();}
        public async Task Sql(string sql,params(string,object)[] ps){await using var c=Db.Open();await using var q=c.CreateCommand();q.CommandText=sql;foreach(var p in ps)q.Parameters.AddWithValue(p.Item1,p.Item2 is Guid id?id.ToString():p.Item2);await q.ExecuteNonQueryAsync();}
        public void Dispose(){SqliteConnection.ClearAllPools();if(Directory.Exists(Root))Directory.Delete(Root,true);}
    }
}
