using OncaPDV.Domain;using OncaPDV.Fiscal;using OncaPDV.Printing;
namespace OncaPDV.Tests;
public sealed class DeploymentHardwareTests
{
 private static readonly ReceiptDocument Document=new(null,"ONCA",Cut:false,OpenDrawer:false,DiagnosticLines:["ONCA","TESTE DE IMPRESSAO","IMPRESSORA OK"]);
 [Theory][InlineData("offline")][InlineData("spooler")][InlineData("write")][InlineData("partial")][InlineData("paper")]
 public async Task Printer_failures_do_not_change_business_state_and_allow_reprint(string failure){var transport=new FailureTransport(failure);var dir=Path.Combine(Path.GetTempPath(),"onca-hardware-"+Guid.NewGuid());try{var service=new WindowsRawPrintService(new EscPos80Renderer(),dir,true,transport);var result=await service.PrintAsync(Document,"POS-80");Assert.False(result.Success);Assert.Equal(1,transport.BusinessSales);Assert.Equal(1,transport.StockMovements);Assert.Equal(1,transport.CashMovements);var reprint=await new MockPrintService(new EscPos80Renderer(),dir).PrintAsync(Document);Assert.True(reprint.Success);Assert.Equal(1,transport.BusinessSales);}finally{if(Directory.Exists(dir))Directory.Delete(dir,true);}}
 [Theory][InlineData(850)][InlineData(858)][InlineData(860)]public async Task Accented_diagnostic_is_valid_in_mock_only(int cp){var dir=Path.Combine(Path.GetTempPath(),"onca-accent-"+Guid.NewGuid());try{var lines=new[]{"ONÇA PRODUTOS DE LIMPEZA","IMPRESSÃO","CRÉDITO","DÉBITO","DESCRIÇÃO","CORAÇÃO","AÇÃO"};var renderer=new EscPos80Renderer(new CodePagePrinterEncoding(cp));var rendered=renderer.Render(new ReceiptDocument(null,Cut:false,OpenDrawer:false,DiagnosticLines:lines));Assert.True(rendered.Bytes.Length>0);Assert.DoesNotContain(new byte[]{0x1d,0x56},rendered.Bytes);Assert.True((await new MockPrintService(renderer,dir).PrintAsync(new ReceiptDocument(null,Cut:false,OpenDrawer:false,DiagnosticLines:lines))).Success);}finally{if(Directory.Exists(dir))Directory.Delete(dir,true);}}
 [Fact]public void Approved_mock_payload_is_exact_and_uses_lf_only(){var bytes=new EscPos80Renderer(CodePagePrinterEncoding.Cp850()).Render(Document).Bytes;Assert.Equal("1B404F4E43410A544553544520444520494D5052455353414F0A494D50524553534F5241204F4B0A1B6402",Convert.ToHexString(bytes));Assert.Equal(new byte[]{0x1B,0x40},bytes[..2]);Assert.Equal(3,bytes.Count(value=>value==0x0A));Assert.DoesNotContain((byte)0x0D,bytes);}
 [Fact]public void Prepared_plain_ascii_payload_has_only_text_and_crlf(){var bytes=PlainAsciiDiagnosticPayload.Create();Assert.Equal(PlainAsciiDiagnosticPayload.Hex,Convert.ToHexString(bytes));Assert.DoesNotContain((byte)0x1B,bytes);Assert.Equal(39,bytes.Length);Assert.Equal(3,bytes.Count(value=>value==0x0D));Assert.Equal(3,bytes.Count(value=>value==0x0A));}
 [Fact]public void Terminal_printer_profile_supports_future_backend_choice(){var profile=new PrinterTerminalProfile("CAIXA-01","POS-80","USB001",80,PrintBackend.EscPosRaw,"ASCII",false,false);Assert.Equal("CAIXA-01",profile.TerminalId);Assert.Equal("USB001",profile.PrinterPort);Assert.Equal(PrintBackend.EscPosRaw,profile.PrintBackend);Assert.False(profile.CutEnabled);Assert.False(profile.DrawerEnabled);}
 [Theory][InlineData("single")][InlineData("multiple")][InlineData("long")][InlineData("cash")][InlineData("change")][InlineData("pix")][InlineData("card")][InlineData("credit")][InlineData("mixed")][InlineData("reprint")]
 public async Task Real_80mm_receipt_scenarios_render_in_mock_through_same_print_service(string scenario)
 {
  var dir=Path.Combine(Path.GetTempPath(),"onca-real-receipt-"+Guid.NewGuid());try{var sale=ReceiptSale(scenario);IPrintService printService=new MockPrintService(new EscPos80Renderer(CodePagePrinterEncoding.Cp850()),dir);var document=new ReceiptDocument(sale,CustomerName:scenario=="single"?"CLIENTE TESTE":null,Cut:false,OpenDrawer:false,OperatorName:"OPERADOR 01",IsReprint:scenario=="reprint");var result=await printService.PrintAsync(document);Assert.True(result.Success);var preview=await File.ReadAllTextAsync(result.PreviewPath!);Assert.Contains("ONCA PRODUTOS DE LIMPEZA",preview);Assert.Contains($"Venda: {sale.Number:00000}",preview);Assert.Contains("PRODUTOS",preview);Assert.Contains("TOTAL: R$",preview);Assert.Contains("Pagamento:",preview);Assert.Contains("Recebido:",preview);Assert.Contains("Troco:",preview);Assert.Contains("OBRIGADO PELA PREFERENCIA",preview);if(scenario=="mixed"){Assert.Contains("PIX",preview);Assert.Contains("Dinheiro",preview);}if(scenario=="credit")Assert.Contains("Crediario",preview);if(scenario=="reprint")Assert.Contains("REIMPRESSAO / SEGUNDA VIA",preview);var bin=Directory.GetFiles(dir,"*.bin").Single();var bytes=await File.ReadAllBytesAsync(bin);Assert.Equal(new byte[]{0x1B,0x40},bytes[..2]);Assert.DoesNotContain(new byte[]{0x1D,0x56},bytes);Assert.DoesNotContain(new byte[]{0x1B,0x70},bytes);}finally{if(Directory.Exists(dir))Directory.Delete(dir,true);}
 }
 private static Sale ReceiptSale(string scenario){var names=scenario switch{"multiple"=>new[]{"DETERGENTE","DESINFETANTE","ESPONJA"},"long"=>new[]{"PRODUTO COM NOME MUITO LONGO PARA VALIDAR O LIMITE DO CUPOM TERMICO DE OITENTA MILIMETROS"},_=>new[]{"DETERGENTE NEUTRO"}};var items=names.Select((name,index)=>new CartItem(Guid.NewGuid(),$"P{index+1}",name,index+1,12.50m)).ToArray();var total=items.Sum(x=>x.Subtotal);Payment[] payments=scenario switch{"pix"=>[new(PaymentMethod.Pix,total)],"card"=>[new(PaymentMethod.Credit,total)],"credit"=>[new(PaymentMethod.StoreCredit,total)],"mixed"=>[new(PaymentMethod.Pix,10),new(PaymentMethod.Cash,total-10,total)],"change"=>[new(PaymentMethod.Cash,total,total+20)],_=>[new(PaymentMethod.Cash,total,total)]};return new(Guid.NewGuid(),12345,DateTimeOffset.Now,Guid.NewGuid(),null,items,payments,0,total);}
 [Fact]public void Controlled_real_receipt_payload_is_single_nonempty_80mm_cp850_without_cut_or_drawer(){var sale=new Sale(Guid.NewGuid(),1,DateTimeOffset.Now,Guid.Empty,null,[new(Guid.NewGuid(),"A","DETERGENTE TESTE",1,5),new(Guid.NewGuid(),"B","DESINFETANTE TESTE",1,10)],[new(PaymentMethod.Cash,15,20)],0,15);var document=new ReceiptDocument(sale,Cut:false,OpenDrawer:false,OperatorName:"TESTE",SaleLabel:"TESTE-001");var receipt=new EscPos80Renderer(CodePagePrinterEncoding.Cp850()).Render(document);ReceiptValidator.EnsurePrintable(receipt);Assert.Equal("80mm",receipt.Media);Assert.Contains("Venda: TESTE-001",receipt.Text);Assert.Contains("TOTAL: R$ 15,00",receipt.Text);Assert.Contains("R$ 20,00",receipt.Text);Assert.Contains("R$ 5,00",receipt.Text);Assert.DoesNotContain(new byte[]{0x1D,0x56},receipt.Bytes);Assert.DoesNotContain(new byte[]{0x1B,0x70},receipt.Bytes);Assert.NotEmpty(receipt.Bytes);}
 [Theory][InlineData("simple")][InlineData("multiple")][InlineData("discount")][InlineData("identified")][InlineData("consumer")][InlineData("pix")][InlineData("cash")][InlineData("card")][InlineData("mixed")]
 public void Fiscal_xml_fixtures_are_built_without_sefaz(string scenario){var sale=SaleFor(scenario);var xml=FiscalXmlBuilder.Build(sale,Config());Assert.Contains("<mod>65</mod>",xml);Assert.Contains($"<vNF>{sale.Total.ToString("0.00",System.Globalization.CultureInfo.InvariantCulture)}</vNF>",xml);Assert.Equal(sale.Items.Count,System.Text.RegularExpressions.Regex.Matches(xml,"<det nItem=").Count);}
 [Fact]public async Task Fiscal_rejection_timeout_contingency_and_cancel_are_isolated_from_sale(){var sale=SaleFor("simple");var store=new MemoryStore();var rejected=await new FiscalService(new HomologacaoFiscalProvider(Config(),new Secrets(),new Signer(),new Transport("reject")),store).IssueAsync(sale);Assert.Equal(FiscalStatus.Rejected,rejected.Status);var timeout=await new FiscalService(new HomologacaoFiscalProvider(Config(),new Secrets(),new Signer(),new Transport("timeout")),store).IssueAsync(sale);Assert.Equal(FiscalStatus.Contingency,timeout.Status);Assert.Equal(100,sale.Total);Assert.Single(sale.Items);Assert.True(store.Results.Count>=4);}
 [Fact]public async Task Homologation_transport_is_disabled_by_default(){await Assert.ThrowsAsync<InvalidOperationException>(()=>new DisabledHomologationTransport().SendAsync("<xml/>"));}
 private static FiscalConfiguration Config()=>new("11222333000181","123456789",1,new("Rua A","1","Centro","São Paulo","3550308","SP","01000000"),"secret://csc","1","secret://certificate","secret://certificate-password",1,1,"Homologacao");
 private static Sale SaleFor(string scenario){var count=scenario=="multiple"?3:1;var items=Enumerable.Range(1,count).Select(i=>new CartItem(Guid.NewGuid(),$"P{i}",$"Produto {i}",1,100m/count)).ToArray();var payments=scenario switch{"pix"=>new[]{new Payment(PaymentMethod.Pix,100)},"cash"=>new[]{new Payment(PaymentMethod.Cash,100,120)},"card"=>new[]{new Payment(PaymentMethod.Credit,100)},"mixed"=>new[]{new Payment(PaymentMethod.Pix,30),new Payment(PaymentMethod.Cash,70,100)},_=>new[]{new Payment(PaymentMethod.Cash,100,100)}};return new(Guid.NewGuid(),1,DateTimeOffset.Now,Guid.NewGuid(),scenario=="consumer"?null:Guid.NewGuid(),items,payments,scenario=="discount"?10:0,100);}
 private sealed class FailureTransport(string mode):IPhysicalPrinterTransport{public int BusinessSales=>1;public int StockMovements=>1;public int CashMovements=>1;public PrinterAvailability GetAvailability(string name)=>mode is "offline" or "paper"?PrinterAvailability.Offline:PrinterAvailability.Online;public SpoolerTrace Send(string name,byte[] bytes){if(mode=="spooler")throw new IOException("Spooler indisponível.");if(mode=="write")return new(true,true,true,false,false,false,bytes.Length,0,5);if(mode=="partial")return new(true,true,true,true,true,true,bytes.Length,bytes.Length-1,0);return new(false,false,false,false,false,false,bytes.Length,0,21);}}
 private sealed class Secrets:IFiscalSecretStore{public Task<byte[]> ReadAsync(string r,CancellationToken ct=default)=>Task.FromResult(System.Text.Encoding.UTF8.GetBytes("fixture"));}
 private sealed class Signer:IFiscalSigner{public Task<string> SignAsync(string xml,byte[] cert,ReadOnlyMemory<char> password,CancellationToken ct=default)=>Task.FromResult(xml.Replace("</NFe>","<Signature>FIXTURE</Signature></NFe>"));}
 private sealed class Transport(string mode):IHomologationTransport{public Task<FiscalResult> SendAsync(string xml,CancellationToken ct=default)=>mode=="timeout"?Task.FromCanceled<FiscalResult>(new(true)):Task.FromResult(new FiscalResult(FiscalStatus.Rejected,Error:"REJEIÇÃO FIXTURE"));}
 private sealed class MemoryStore:IFiscalDocumentStore{public List<FiscalResult> Results{get;}=[];public Task SaveAsync(Guid id,FiscalResult result,string? xml,CancellationToken ct=default){Results.Add(result);return Task.CompletedTask;}}
}
