using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using OncaPDV.Domain;
using OncaPDV.Fiscal;

namespace OncaPDV.Tests;

public sealed class FiscalHomologationTests
{
 [Theory][InlineData(FiscalModels.NFCe)][InlineData(FiscalModels.NFe)]
 public void Xml_models_are_generated_and_validated_only_in_homologation(string model){var xml=FiscalXmlBuilder.Build(Sale(),Config(),model);FiscalXmlValidator.Validate(xml,model,false);Assert.Contains($"<mod>{model}</mod>",xml);Assert.Contains("<tpAmb>2</tpAmb>",xml);Assert.Contains("versao=\"4.00\"",xml);}
 [Fact]public void Production_configuration_is_blocked(){Assert.Throws<InvalidOperationException>(()=>(Config() with{Environment="Producao"}).Validate());}
 [Fact]public async Task Mock_is_explicitly_non_fiscal_and_supports_both_models(){var provider=new MockFiscalProvider();foreach(var model in new[]{FiscalModels.NFCe,FiscalModels.NFe}){var result=await provider.IssueAsync(new(Sale(),model,"Homologacao"));Assert.True(result.IsMock);Assert.Equal(FiscalStatus.Authorized,result.Status);Assert.Contains("semValorFiscal=\"true\"",result.AuthorizedXml);}}
 [Fact]public async Task Mock_never_authorizes_production(){var result=await new MockFiscalProvider().IssueAsync(new(Sale(),FiscalModels.NFCe,"Producao"));Assert.Equal(FiscalStatus.Rejected,result.Status);Assert.Contains("Produção bloqueada",result.Error);}
 [Fact]public async Task A1_signature_is_generated_and_detected(){using var rsa=RSA.Create(2048);var request=new CertificateRequest("CN=ONCA TESTE",rsa,HashAlgorithmName.SHA256,RSASignaturePadding.Pkcs1);using var cert=request.CreateSelfSigned(DateTimeOffset.UtcNow.AddDays(-1),DateTimeOffset.UtcNow.AddDays(2));var pfx=cert.Export(X509ContentType.Pfx,"fixture");var signed=await new A1FiscalSigner().SignAsync(FiscalXmlBuilder.Build(Sale(),Config()),pfx,"fixture".AsMemory());FiscalXmlValidator.Validate(signed,FiscalModels.NFCe,true);Assert.Contains("Signature",signed);}
 [Fact]public async Task Query_cancel_and_rejection_codes_are_propagated(){var transport=new Transport();var provider=new HomologacaoFiscalProvider(Config(),new Secrets(),new FixtureSigner(),transport);var query=await provider.QueryAsync("KEY","Homologacao");var cancel=await provider.CancelAsync("KEY","PROTO","Cancelamento solicitado em teste", "Homologacao");Assert.Equal("100",query.RejectionCode);Assert.Equal(FiscalStatus.Cancelled,cancel.Status);}
 [Fact]public async Task Sale_survives_fiscal_failure_and_only_authorized_xml_is_persisted(){var sale=Sale();var store=new MemoryStore();var result=await new FiscalService(new RejectProvider(),store).IssueAsync(sale);Assert.Equal(FiscalStatus.Rejected,result.Status);Assert.Equal(100,sale.Total);Assert.All(store.Xml,Assert.Null);}
 [Fact]public void Danfe_requires_valid_authorization_and_marks_mock(){Assert.Throws<InvalidOperationException>(()=>DanfeHomologationRenderer.Render(new(FiscalStatus.Rejected),FiscalModels.NFCe));var result=new FiscalResult(FiscalStatus.Authorized,"KEY","PROTO","<mock/>",IsMock:true);var danfe=DanfeHomologationRenderer.Render(result,FiscalModels.NFCe);Assert.Contains("HOMOLOGACAO - SEM VALOR FISCAL",danfe);Assert.Contains("SIMULACAO MOCK",danfe);}
 [Fact]public async Task Authorized_xml_and_protocol_are_saved_atomically(){var root=Path.Combine(Path.GetTempPath(),"onca-fiscal-"+Guid.NewGuid());try{var store=new FileFiscalDocumentStore(root);var id=Guid.NewGuid();await store.SaveAsync(id,new(FiscalStatus.Authorized,"KEY","PROTO","<nfe/>",IsMock:true),"<nfe/>");Assert.Single(Directory.GetFiles(Path.Combine(root,id.ToString("N")),"*-autorizado.xml"));Assert.Single(Directory.GetFiles(Path.Combine(root,id.ToString("N")),"*.json"));}finally{if(Directory.Exists(root))Directory.Delete(root,true);}}
 [Fact]public async Task Invalid_cancel_reason_never_reaches_transport(){var transport=new Transport();var provider=new HomologacaoFiscalProvider(Config(),new Secrets(),new FixtureSigner(),transport);var result=await provider.CancelAsync("KEY","PROTO","curta","Homologacao");Assert.Equal(FiscalStatus.Rejected,result.Status);Assert.Equal(0,transport.CancelCalls);}
 private static FiscalConfiguration Config()=>new("11222333000181","123456789",1,new("Rua A","1","Centro","Sao Paulo","3550308","SP","01000000"),"secret://csc","1","secret://certificate","secret://certificate-password",1,1,"Homologacao",2,1);
 private static Sale Sale()=>new(Guid.NewGuid(),1,DateTimeOffset.Now,Guid.NewGuid(),null,[new(Guid.NewGuid(),"P1","PRODUTO",1,100)],[new(PaymentMethod.Cash,100,100)],0,100);
 private sealed class Secrets:IFiscalSecretStore{public Task<byte[]> ReadAsync(string r,CancellationToken ct=default)=>Task.FromResult(Encoding.UTF8.GetBytes("fixture"));}
 private sealed class FixtureSigner:IFiscalSigner{public Task<string> SignAsync(string xml,byte[] c,ReadOnlyMemory<char> p,CancellationToken ct=default)=>Task.FromResult(xml.Replace("</NFe>","<Signature xmlns=\"http://www.w3.org/2000/09/xmldsig#\" /></NFe>"));}
 private sealed class Transport:IHomologationTransport{public int CancelCalls;public Task<FiscalResult> SendAsync(string xml,CancellationToken ct=default)=>Task.FromResult(new FiscalResult(FiscalStatus.Rejected,Error:"Rejeitado",RejectionCode:"999"));public Task<FiscalResult> QueryAsync(string key,CancellationToken ct=default)=>Task.FromResult(new FiscalResult(FiscalStatus.Authorized,key,"PROTO",RejectionCode:"100"));public Task<FiscalResult> CancelAsync(string key,string protocol,string reason,CancellationToken ct=default){CancelCalls++;return Task.FromResult(new FiscalResult(FiscalStatus.Cancelled,key,protocol,RejectionCode:"135"));}}
 private sealed class RejectProvider:IFiscalProvider{public Task<FiscalResult> IssueAsync(FiscalRequest request,CancellationToken ct=default)=>Task.FromResult(new FiscalResult(FiscalStatus.Rejected,Error:"Rejeição",RejectionCode:"999"));}
 private sealed class MemoryStore:IFiscalDocumentStore{public List<string?> Xml{get;}=[];public Task SaveAsync(Guid saleId,FiscalResult result,string? xml,CancellationToken ct=default){Xml.Add(xml);return Task.CompletedTask;}}
}
