using OncaPDV.PostgreSql;
namespace OncaPDV.Tests;
public sealed class MultiCashPostgresTests
{
 [Fact]public void Central_mode_rejects_sqlite_and_requires_terminal(){Assert.ThrowsAny<Exception>(()=>new CentralDatabaseOptions("Data Source=shared.db","CAIXA-01").Validate());Assert.Throws<ArgumentException>(()=>new CentralDatabaseOptions("Host=server;Database=onca;Username=onca"," ").Validate());new CentralDatabaseOptions("Host=server;Database=onca;Username=onca","CAIXA-01").Validate();}
 [Fact]public void Schema_shares_business_data_and_separates_terminals(){var sql=PostgresSchema.Sql;foreach(var table in new[]{"products","customers","suppliers","sales","payments","cash_movements","stock_movements","credit_accounts","credit_receipts","purchases","purchase_items"})Assert.Contains($"TABLE IF NOT EXISTS {table}",sql);foreach(var terminal in new[]{"CAIXA-01","CAIXA-02","CAIXA-03","ADMIN"})Assert.Contains(terminal,sql);Assert.Contains("terminal_id text NOT NULL",sql);Assert.Contains("operation_id uuid NOT NULL UNIQUE",sql);Assert.Contains("number bigint NOT NULL UNIQUE",sql);Assert.Contains("sale_number_seq",sql);Assert.Contains("ux_open_cash_terminal_operator",sql);}
 [Fact]public async Task Unavailable_server_is_explicit_and_does_not_create_local_database(){var local=Path.Combine(Path.GetTempPath(),"onca-central-must-not-exist-"+Guid.NewGuid()+".db");await using var db=new PostgresCentralDatabase(new CentralDatabaseOptions("Host=127.0.0.1;Port=1;Database=onca;Username=none;Password=none;Timeout=1;Command Timeout=1","CAIXA-01",1));var ex=await Assert.ThrowsAsync<CentralDatabaseUnavailableException>(()=>db.EnsureAvailableAsync());Assert.Contains("nenhum fallback local",ex.Message);Assert.False(File.Exists(local));}
 [Fact]public void Concurrency_contract_uses_serializable_idempotency_sequence_and_atomic_stock(){var source=File.ReadAllText(Path.Combine(FindRoot(),"src","OncaPDV.PostgreSql","CentralDatabase.cs"));Assert.Contains("IsolationLevel.Serializable",source);Assert.Contains("WHERE operation_id=@operation",source);Assert.Contains("nextval('sale_number_seq')",source);Assert.Contains("stock=stock-@quantity",source);Assert.Contains("stock>=@quantity RETURNING stock",source);Assert.Contains("SerializationFailure",source);Assert.Contains("DeadlockDetected",source);Assert.Contains("INSERT INTO cash_movements",source);Assert.Contains("INSERT INTO credit_accounts",source);}
 private static string FindRoot(){var dir=new DirectoryInfo(AppContext.BaseDirectory);while(dir is not null&&!File.Exists(Path.Combine(dir.FullName,"OncaPDV.slnx")))dir=dir.Parent;return dir?.FullName??throw new DirectoryNotFoundException();}
}
