<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.1" />
    <ProjectReference Include="..\..\src\OncaPDV.Domain\OncaPDV.Domain.csproj" />
    <ProjectReference Include="..\..\src\OncaPDV.Application\OncaPDV.Application.csproj" />
    <ProjectReference Include="..\..\src\OncaPDV.Infrastructure\OncaPDV.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\OncaPDV.Printing\OncaPDV.Printing.csproj" />
    <ProjectReference Include="..\..\src\OncaPDV.Fiscal\OncaPDV.Fiscal.csproj" />
    <ProjectReference Include="..\..\src\OncaPDV.Migration\OncaPDV.Migration.csproj" />
    <ProjectReference Include="..\..\src\OncaPDV.PostgreSql\OncaPDV.PostgreSql.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
