using System.Globalization;
using System.Windows;
using System.Windows.Controls;
using OncaPDV.Infrastructure;
namespace OncaPDV.Desktop;
public partial class Finance052Window:Window
{
    private readonly Finance052 _service;private readonly OncaDatabase _db;private readonly Guid _operator;private bool _loading;private bool _saving;
    private static readonly string[] Categories=["Fornecedores","Aluguel","Energia","Água","Internet / Telefone","Combustível","Manutenção","Material de uso","Impostos / Taxas","Frete","Marketing","Outros"];
    private static readonly string[] Methods=["Dinheiro","PIX","Débito","Crédito","Boleto","Transferência","Outro"];
    public Finance052Window(OncaDatabase db,Guid op){InitializeComponent();_db=db;_operator=op;_service=new(db);PayCategory.ItemsSource=Categories;ExpenseCategory.ItemsSource=Categories;PayPaymentMethod.ItemsSource=Methods;ExpenseMethod.ItemsSource=Methods;PayFilter.ItemsSource=new[]{"Todos","Pendentes","Vencidos","Pagos","Cancelados"};PayFilter.SelectedIndex=0;PayPaymentMethod.SelectedIndex=0;ExpenseMethod.SelectedIndex=1;PayFirstDue.SelectedDate=DateTime.Today;ExpenseDate.SelectedDate=DateTime.Today;Loaded+=async(_,_)=>await LoadAll();}
    private async Task LoadAll()
    {if(_loading)return;_loading=true;try{PayablesGrid.ItemsSource=await _service.PayablesAsync(PayFilter.SelectedItem?.ToString()??"Todos");var now=DateTimeOffset.Now;var from=new DateTimeOffset(now.Year,now.Month,1,0,0,0,now.Offset);ExpensesGrid.ItemsSource=await _service.ExpensesAsync(from,from.AddMonths(1));var s=await _service.SummaryAsync();SummaryText.Text=$"Em aberto: {s.OpenPayables:C} ({s.OpenCount} conta(s))   •   Vencido: {s.OverduePayables:C} ({s.OverdueCount})   •   Pago em contas neste mês: {s.PaidThisMonth:C}\nDespesas do mês: {s.ExpensesThisMonth:C}   •   Despesas em dinheiro: {s.CashExpensesThisMonth:C}";}catch(Exception ex){MessageBox.Show(ex.Message,"Financeiro",MessageBoxButton.OK,MessageBoxImage.Warning);}finally{_loading=false;}}
    private static decimal Money(string text){if(decimal.TryParse(text,NumberStyles.Number,CultureInfo.GetCultureInfo("pt-BR"),out var v)||decimal.TryParse(text,NumberStyles.Number,CultureInfo.CurrentCulture,out v))return v;throw new InvalidOperationException("Valor inválido.");}
    private static DateTimeOffset Date(DatePicker p){var d=p.SelectedDate??DateTime.Today;return new DateTimeOffset(d.Year,d.Month,d.Day,0,0,0,DateTimeOffset.Now.Offset);}
    private async void Refresh_Click(object s,RoutedEventArgs e)=>await LoadAll();
    private async void PayFilter_SelectionChanged(object s,SelectionChangedEventArgs e){if(IsLoaded)await LoadAll();}
    private void PayablesGrid_SelectionChanged(object s,SelectionChangedEventArgs e){if(PayablesGrid.SelectedItem is PayableView052 p)PayPaymentAmount.Text=p.Remaining.ToString("N2");}
    private async void CreatePayable_Click(object s,RoutedEventArgs e)
    {if(_saving)return;_saving=true;try{var count=int.TryParse(PayInstallments.Text,out var n)?n:0;var rows=await _service.CreateInstallmentsAsync(PaySupplier.Text,PayDescription.Text,PayCategory.Text,Money(PayTotal.Text),Date(PayFirstDue),count,PayDocument.Text,PayNotes.Text,_operator);MessageBox.Show($"{rows.Count} parcela(s) cadastrada(s) com sucesso.","Contas a pagar");PayDescription.Clear();PayTotal.Clear();PayDocument.Clear();PayNotes.Clear();await LoadAll();}catch(Exception ex){MessageBox.Show(ex.Message,"Contas a pagar",MessageBoxButton.OK,MessageBoxImage.Warning);}finally{_saving=false;}}
    private async void PaySelected_Click(object s,RoutedEventArgs e)
    {if(_saving)return;if(PayablesGrid.SelectedItem is not PayableView052 p){MessageBox.Show("Selecione uma conta a pagar.");return;}_saving=true;try{var amount=Money(PayPaymentAmount.Text);var method=PayPaymentMethod.SelectedItem?.ToString()??"";var result=await _service.PayAsync(p.Id,amount,method,PayPaymentNotes.Text,_operator,Guid.NewGuid());MessageBox.Show($"Pagamento registrado: {result.Amount:C} via {result.Method}.","Financeiro");PayPaymentNotes.Clear();await LoadAll();}catch(Exception ex){MessageBox.Show(ex.Message,"Pagamento",MessageBoxButton.OK,MessageBoxImage.Warning);}finally{_saving=false;}}
    private async void CancelPayable_Click(object s,RoutedEventArgs e)
    {if(_saving)return;if(PayablesGrid.SelectedItem is not PayableView052 p){MessageBox.Show("Selecione uma conta.");return;}var auth=new AdminAuthorization040Window(_db){Owner=this};if(auth.ShowDialog()!=true)return;var reason=Microsoft.VisualBasic.Interaction.InputBox("Motivo obrigatório do cancelamento:","Cancelar conta a pagar","").Trim();if(reason.Length<4)return;if(MessageBox.Show($"Cancelar a conta {p.Supplier} — {p.Remaining:C}?\n\nContas com pagamentos já registrados não serão apagadas.","Financeiro",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return;_saving=true;try{await _service.CancelPayableAsync(p.Id,_operator,$"ADMIN: {auth.AuthorizedName} | {reason}");await LoadAll();}catch(Exception ex){MessageBox.Show(ex.Message,"Cancelar conta",MessageBoxButton.OK,MessageBoxImage.Warning);}finally{_saving=false;}}
    private async void AddExpense_Click(object s,RoutedEventArgs e)
    {if(_saving)return;_saving=true;try{var result=await _service.AddExpenseAsync(ExpenseCategory.Text,ExpenseDescription.Text,Money(ExpenseAmount.Text),ExpenseMethod.SelectedItem?.ToString()??"",Date(ExpenseDate),ExpenseSupplier.Text,ExpenseDocument.Text,ExpenseNotes.Text,_operator,Guid.NewGuid());MessageBox.Show($"Despesa registrada: {result.Amount:C} via {result.Method}.","Despesas");ExpenseDescription.Clear();ExpenseAmount.Clear();ExpenseDocument.Clear();ExpenseNotes.Clear();await LoadAll();}catch(Exception ex){MessageBox.Show(ex.Message,"Despesas",MessageBoxButton.OK,MessageBoxImage.Warning);}finally{_saving=false;}}
}
