using System.Collections.ObjectModel;
using System.Windows;
using OncaPDV.Domain;
using OncaPDV.Infrastructure;

namespace OncaPDV.Desktop;
public partial class PurchasesWindow:Window
{
 private readonly SupplierService _suppliers;private readonly PurchaseService _purchases;private readonly SqliteProductRepository _products;private readonly ObservableCollection<PurchaseRow> _items=[];
 public PurchasesWindow(OncaDatabase db){InitializeComponent();_suppliers=new(db);_purchases=new(db);_products=new(db);ItemsGrid.ItemsSource=_items;Loaded+=async(_,_)=>await LoadSuppliers();}
 private async Task LoadSuppliers(string term=""){var list=await _suppliers.SearchAsync(term);SupplierGrid.ItemsSource=list;SupplierCombo.ItemsSource=list;if(SupplierCombo.SelectedItem is null&&list.Count>0)SupplierCombo.SelectedIndex=0;}
 private async void SaveSupplier_Click(object sender,RoutedEventArgs e){try{await _suppliers.SaveAsync(new Supplier(Guid.NewGuid(),SupplierName.Text.Trim(),SupplierTax.Text.Trim(),SupplierPhone.Text.Trim(),null));SupplierName.Clear();SupplierTax.Clear();SupplierPhone.Clear();await LoadSuppliers();}catch(Exception ex){MessageBox.Show(ex.Message,"Fornecedor",MessageBoxButton.OK,MessageBoxImage.Warning);}}
 private async void SearchSupplier_Click(object sender,RoutedEventArgs e)=>await LoadSuppliers(SupplierSearch.Text);
 private async void AddItem_Click(object sender,RoutedEventArgs e){try{var product=await _products.FindAsync(ProductSearch.Text.Trim())??throw new DomainException("Produto não encontrado.");if(!decimal.TryParse(Quantity.Text,out var quantity)||quantity<=0||!decimal.TryParse(UnitCost.Text,out var cost)||cost<0)throw new DomainException("Quantidade ou custo inválido.");_items.Add(new(product.Id,product.InternalCode,product.Name,quantity,cost));RefreshTotal();ProductSearch.Clear();UnitCost.Clear();}catch(Exception ex){MessageBox.Show(ex.Message,"Compra",MessageBoxButton.OK,MessageBoxImage.Warning);}}
 private async void ImportPurchase_Click(object sender,RoutedEventArgs e){var dlg=new Microsoft.Win32.OpenFileDialog{Filter="Nota XML ou CSV|*.xml;*.csv|XML NF-e|*.xml|CSV|*.csv"};if(dlg.ShowDialog()!=true)return;try{var imported=0;if(System.IO.Path.GetExtension(dlg.FileName).Equals(".xml",StringComparison.OrdinalIgnoreCase)){var doc=System.Xml.Linq.XDocument.Load(dlg.FileName);var dets=doc.Descendants().Where(x=>x.Name.LocalName=="det");foreach(var det in dets){var prod=det.Descendants().FirstOrDefault(x=>x.Name.LocalName=="prod");if(prod is null)continue;string V(string n)=>prod.Elements().FirstOrDefault(x=>x.Name.LocalName==n)?.Value??"";var code=V("cProd");var name=V("xProd");if(!decimal.TryParse(V("qCom"),System.Globalization.NumberStyles.Any,System.Globalization.CultureInfo.InvariantCulture,out var q)||q<=0)continue;if(!decimal.TryParse(V("vUnCom"),System.Globalization.NumberStyles.Any,System.Globalization.CultureInfo.InvariantCulture,out var cost)||cost<0)continue;var product=await _products.FindAsync(code)??await _products.FindAsync(name);if(product is null)continue;_items.Add(new(product.Id,product.InternalCode,product.Name,q,cost));imported++;}var n=doc.Descendants().FirstOrDefault(x=>x.Name.LocalName=="nNF")?.Value;if(!string.IsNullOrWhiteSpace(n))DocumentNumber.Text=n;}else{foreach(var line in System.IO.File.ReadLines(dlg.FileName).Skip(1)){var f=line.Split(';',',');if(f.Length<3)continue;var product=await _products.FindAsync(f[0].Trim());if(product is null)continue;if(!decimal.TryParse(f[1],out var q)||q<=0||!decimal.TryParse(f[2],out var cost)||cost<0)continue;_items.Add(new(product.Id,product.InternalCode,product.Name,q,cost));imported++;}}RefreshTotal();MessageBox.Show($"{imported} item(ns) importado(s) para conferência. O estoque só será alterado ao clicar CONFIRMAR ENTRADA.");}catch(Exception ex){MessageBox.Show(ex.Message,"Importar compra",MessageBoxButton.OK,MessageBoxImage.Warning);}}
 private async void CompletePurchase_Click(object sender,RoutedEventArgs e){try{if(SupplierCombo.SelectedItem is not Supplier supplier)throw new DomainException("Selecione o fornecedor.");var purchase=await _purchases.CompleteAsync(supplier.Id,_items.Select(x=>new PurchaseItem(x.ProductId,x.Code,x.Name,x.Quantity,x.UnitCost)).ToArray(),DocumentNumber.Text.Trim());MessageBox.Show($"Compra Nº {purchase.Number:000000} concluída.\nEstoque atualizado: {purchase.Total:C}");_items.Clear();DocumentNumber.Clear();RefreshTotal();}catch(Exception ex){MessageBox.Show(ex.Message,"Compra",MessageBoxButton.OK,MessageBoxImage.Warning);}}
 private void RefreshTotal()=>PurchaseTotal.Text=$"TOTAL: {_items.Sum(x=>x.Subtotal):C}";
 private sealed record PurchaseRow(Guid ProductId,string Code,string Name,decimal Quantity,decimal UnitCost){public decimal Subtotal=>Quantity*UnitCost;}
}
