using System.Text.Json;
using Microsoft.Data.Sqlite;
using OncaPDV.Application;
using OncaPDV.Domain;

namespace OncaPDV.Infrastructure;

public sealed record SaleSearchRow(Guid Id,long Number,DateTimeOffset CreatedAt,string Customer,decimal Total,string Payments,string Status,string FiscalStatus);
public sealed record CashMovementView(Guid Id,DateTimeOffset CreatedAt,string Type,decimal Amount,string Reason,Guid? OriginId);
public sealed record QuoteView(Guid Id,long Number,DateTimeOffset CreatedAt,string Customer,decimal Total,string Status,DateTimeOffset? ValidUntil);
public sealed record FiscalDraftView(Guid Id,Guid SaleId,long SaleNumber,DateTimeOffset CreatedAt,string Status,decimal Total,string Customer);

public sealed class AdvancedOperationsService(OncaDatabase db,IClock? clock=null)
{
    private readonly IClock _clock=clock??new SystemClock();

    public async Task<IReadOnlyList<SaleSearchRow>> SearchSalesAsync(string term="",string status="Todos",CancellationToken ct=default)
    {
        var list=new List<SaleSearchRow>();await using var c=db.Open();await using var q=c.CreateCommand();
        q.CommandText="""
SELECT s.id,s.number,s.created_at,COALESCE(cu.name,'CONSUMIDOR'),s.total,s.status,s.fiscal_status,
COALESCE((SELECT group_concat(method, ' + ') FROM payments p WHERE p.sale_id=s.id),'')
FROM sales s LEFT JOIN customers cu ON cu.id=s.customer_id
WHERE ($status='Todos' OR s.status=$status) AND (
CAST(s.number AS TEXT) LIKE $q OR COALESCE(cu.name,'') LIKE $q OR CAST(s.total AS TEXT) LIKE $q OR
EXISTS(SELECT 1 FROM sale_items i WHERE i.sale_id=s.id AND (i.name LIKE $q OR i.code LIKE $q)) OR
EXISTS(SELECT 1 FROM payments p WHERE p.sale_id=s.id AND p.method LIKE $q))
ORDER BY s.number DESC LIMIT 500
""";
        q.Parameters.AddWithValue("$status",status);q.Parameters.AddWithValue("$q",$"%{term.Trim()}%");
        await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(Guid.Parse(r.GetString(0)),r.GetInt64(1),DateTimeOffset.Parse(r.GetString(2)),r.GetString(3),r.GetDecimal(4),r.GetString(7),r.GetString(5),r.GetString(6)));return list;
    }

    public async Task CancelSaleAsync(Guid saleId,Guid operatorId,string reason,CancellationToken ct=default)
    {
        if(string.IsNullOrWhiteSpace(reason))throw new DomainException("Informe o motivo do cancelamento.");
        await using var c=db.Open();await using var tx=(SqliteTransaction)await c.BeginTransactionAsync(ct);
        var status=await ScalarText(c,tx,"SELECT status FROM sales WHERE id=$id",("$id",saleId),ct)??throw new DomainException("Venda não encontrada.");
        if(status=="Cancelled")throw new DomainException("Esta venda já está cancelada.");
        var now=_clock.Now.ToString("O");
        var rows=new List<(Guid ProductId,string Code,decimal Quantity)>();await using(var q=c.CreateCommand()){q.Transaction=tx;q.CommandText="SELECT product_id,code,quantity FROM sale_items WHERE sale_id=$id";q.Parameters.AddWithValue("$id",saleId.ToString());await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))rows.Add((Guid.Parse(r.GetString(0)),r.GetString(1),r.GetDecimal(2)));}
        foreach(var row in rows.Where(x=>!string.Equals(x.Code,"DIVERSOS",StringComparison.OrdinalIgnoreCase))){await Exec(c,tx,"UPDATE products SET stock=stock+$q WHERE id=$p",ct,("$q",row.Quantity),("$p",row.ProductId));await Exec(c,tx,"INSERT INTO stock_movements VALUES($id,$product,'Cancellation',$q,$sale,'ESTORNO VENDA CANCELADA',$at)",ct,("$id",Guid.NewGuid()),("$product",row.ProductId),("$q",row.Quantity),("$sale",saleId),("$at",now));}
        // reverse every cash movement linked to the sale without deleting the original audit trail
        var movements=new List<(Guid Session,string Type,decimal Amount,string Reason)>();await using(var q=c.CreateCommand()){q.Transaction=tx;q.CommandText="SELECT session_id,type,amount,reason FROM cash_movements WHERE origin_id=$sale AND amount>0";q.Parameters.AddWithValue("$sale",saleId.ToString());await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))movements.Add((Guid.Parse(r.GetString(0)),r.GetString(1),r.GetDecimal(2),r.GetString(3)));}
        foreach(var m in movements)await Exec(c,tx,"INSERT INTO cash_movements VALUES($id,$session,$type,$amount,$sale,$reason,$at)",ct,("$id",Guid.NewGuid()),("$session",m.Session),("$type",m.Type),("$amount",-m.Amount),("$sale",saleId),("$reason",$"ESTORNO: {m.Reason}"),("$at",now));
        // reverse credit receipts linked to this sale, then cancel the account and debt
        var accounts=new List<Guid>();await using(var q=c.CreateCommand()){q.Transaction=tx;q.CommandText="SELECT id FROM credit_accounts WHERE sale_id=$sale";q.Parameters.AddWithValue("$sale",saleId.ToString());await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))accounts.Add(Guid.Parse(r.GetString(0)));}
        foreach(var account in accounts)
        {
            var receipts=new List<(Guid Id,decimal Amount)>();await using(var q=c.CreateCommand()){q.Transaction=tx;q.CommandText="SELECT r.id,r.amount FROM credit_receipts r LEFT JOIN credit_receipt_reversals x ON x.receipt_id=r.id WHERE r.account_id=$a AND x.id IS NULL";q.Parameters.AddWithValue("$a",account.ToString());await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))receipts.Add((Guid.Parse(r.GetString(0)),r.GetDecimal(1)));}
            foreach(var receipt in receipts)
            {
                await Exec(c,tx,"INSERT INTO credit_receipt_reversals VALUES($id,$receipt,$account,$amount,$op,$reason,$at)",ct,("$id",Guid.NewGuid()),("$receipt",receipt.Id),("$account",account),("$amount",receipt.Amount),("$op",operatorId),("$reason","ESTORNO AUTOMÁTICO POR CANCELAMENTO DA VENDA"),("$at",now));
                var session=await ScalarText(c,tx,"SELECT session_id FROM cash_movements WHERE origin_id=$a AND type='StoreCreditReceipt' ORDER BY created_at DESC LIMIT 1",("$a",account),ct);
                if(session is not null)await Exec(c,tx,"INSERT INTO cash_movements VALUES($id,$session,'StoreCreditReceipt',$amount,$account,'ESTORNO RECEBIMENTO CREDIÁRIO',$at)",ct,("$id",Guid.NewGuid()),("$session",Guid.Parse(session)),("$amount",-receipt.Amount),("$account",account),("$at",now));
            }
            await Exec(c,tx,"UPDATE credit_accounts SET balance=0,status='Cancelled',notes=COALESCE(notes,'') || $note WHERE id=$id",ct,("$note",$" | Cancelada com venda: {reason}"),("$id",account));
            await Exec(c,tx,"INSERT INTO credit_entries VALUES($id,(SELECT customer_id FROM credit_accounts WHERE id=$account),$sale,'Credit',(SELECT original_amount FROM credit_accounts WHERE id=$account),NULL,$at,'CANCELAMENTO VENDA CREDIÁRIO')",ct,("$id",Guid.NewGuid()),("$account",account),("$sale",saleId),("$at",now));
        }
        await Exec(c,tx,"UPDATE sales SET status='Cancelled',fiscal_status=CASE WHEN fiscal_status='Authorized' THEN 'Cancelled' ELSE fiscal_status END WHERE id=$id",ct,("$id",saleId));
        await AddEvent(c,tx,saleId,operatorId,"Cancelled",reason,null,ct);await tx.CommitAsync(ct);
    }

    public async Task ReverseCreditReceiptAsync(Guid receiptId,Guid operatorId,string reason,CancellationToken ct=default)
    {
        if(string.IsNullOrWhiteSpace(reason))throw new DomainException("Informe o motivo do estorno.");await using var c=db.Open();await using var tx=(SqliteTransaction)await c.BeginTransactionAsync(ct);
        await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="SELECT r.account_id,r.amount FROM credit_receipts r LEFT JOIN credit_receipt_reversals x ON x.receipt_id=r.id WHERE r.id=$id AND x.id IS NULL";q.Parameters.AddWithValue("$id",receiptId.ToString());await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new DomainException("Recebimento não encontrado ou já estornado.");var account=Guid.Parse(r.GetString(0));var amount=r.GetDecimal(1);await r.DisposeAsync();
        var sale=Guid.Parse((await ScalarText(c,tx,"SELECT sale_id FROM credit_accounts WHERE id=$a",("$a",account),ct))!);var now=_clock.Now.ToString("O");
        await Exec(c,tx,"INSERT INTO credit_receipt_reversals VALUES($id,$receipt,$account,$amount,$op,$reason,$at)",ct,("$id",Guid.NewGuid()),("$receipt",receiptId),("$account",account),("$amount",amount),("$op",operatorId),("$reason",reason),("$at",now));
        await Exec(c,tx,"UPDATE credit_accounts SET balance=MIN(original_amount,balance+$amount),status=CASE WHEN balance+$amount>=original_amount THEN 'Open' ELSE 'Partial' END WHERE id=$id AND status<>'Cancelled'",ct,("$amount",amount),("$id",account));
        var session=await ScalarText(c,tx,"SELECT session_id FROM cash_movements WHERE origin_id=$a AND type='StoreCreditReceipt' ORDER BY created_at DESC LIMIT 1",("$a",account),ct);if(session is not null)await Exec(c,tx,"INSERT INTO cash_movements VALUES($id,$session,'StoreCreditReceipt',$amount,$account,'ESTORNO RECEBIMENTO CREDIÁRIO',$at)",ct,("$id",Guid.NewGuid()),("$session",Guid.Parse(session)),("$amount",-amount),("$account",account),("$at",now));
        await AddEvent(c,tx,sale,operatorId,"CreditReceiptReversed",reason,JsonSerializer.Serialize(new{receiptId,amount}),ct);await tx.CommitAsync(ct);
    }

    public async Task ChangeSinglePaymentMethodAsync(Guid saleId,PaymentMethod newMethod,Guid operatorId,string reason,CancellationToken ct=default)
    {
        if(string.IsNullOrWhiteSpace(reason))throw new DomainException("Informe o motivo da alteração.");await using var c=db.Open();await using var tx=(SqliteTransaction)await c.BeginTransactionAsync(ct);
        var saleStatus=await ScalarText(c,tx,"SELECT status FROM sales WHERE id=$id",("$id",saleId),ct);if(saleStatus!="Completed")throw new DomainException("Somente venda concluída pode ter forma de pagamento alterada.");
        var paymentIds=new List<(Guid Id,PaymentMethod Method,decimal Amount)>();await using(var q=c.CreateCommand()){q.Transaction=tx;q.CommandText="SELECT id,method,amount FROM payments WHERE sale_id=$sale";q.Parameters.AddWithValue("$sale",saleId.ToString());await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))paymentIds.Add((Guid.Parse(r.GetString(0)),Enum.Parse<PaymentMethod>(r.GetString(1)),r.GetDecimal(2)));}
        if(paymentIds.Count!=1)throw new DomainException("Venda mista deve ser corrigida pela edição da venda.");var p=paymentIds[0];if(p.Method==newMethod)return;
        var customer=await ScalarText(c,tx,"SELECT customer_id FROM sales WHERE id=$id",("$id",saleId),ct);if(newMethod==PaymentMethod.StoreCredit&&string.IsNullOrWhiteSpace(customer))throw new DomainException("Crediário exige cliente.");
        if(p.Method==PaymentMethod.StoreCredit)
        {
            var active=await ScalarLong(c,tx,"SELECT COUNT(*) FROM credit_receipts r JOIN credit_accounts a ON a.id=r.account_id LEFT JOIN credit_receipt_reversals x ON x.receipt_id=r.id WHERE a.sale_id=$sale AND x.id IS NULL",("$sale",saleId),ct);if(active>0)throw new DomainException("Estorne os recebimentos do crediário antes de alterar a forma de pagamento.");await Exec(c,tx,"UPDATE credit_accounts SET balance=0,status='Cancelled' WHERE sale_id=$sale",ct,("$sale",saleId));
        }
        await Exec(c,tx,"UPDATE payments SET method=$method,received=CASE WHEN $method='Cash' THEN amount ELSE NULL END,change_amount=0 WHERE id=$id",ct,("$method",newMethod.ToString()),("$id",p.Id));
        // neutralize previous sale cash movements and create the new one when needed
        var old=new List<(Guid Session,decimal Amount,string Reason)>();await using(var q=c.CreateCommand()){q.Transaction=tx;q.CommandText="SELECT session_id,amount,reason FROM cash_movements WHERE origin_id=$sale AND type='Sale' AND amount>0";q.Parameters.AddWithValue("$sale",saleId.ToString());await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))old.Add((Guid.Parse(r.GetString(0)),r.GetDecimal(1),r.GetString(2)));}
        foreach(var m in old)await Exec(c,tx,"INSERT INTO cash_movements VALUES($id,$session,'Sale',$amount,$sale,$reason,$at)",ct,("$id",Guid.NewGuid()),("$session",m.Session),("$amount",-m.Amount),("$sale",saleId),("$reason",$"ALTERAÇÃO PAGAMENTO: {m.Reason}"),("$at",_clock.Now.ToString("O")));
        var sessionText=await ScalarText(c,tx,"SELECT cash_session_id FROM sales WHERE id=$sale",("$sale",saleId),ct);if(newMethod!=PaymentMethod.StoreCredit&&sessionText is not null)await Exec(c,tx,"INSERT INTO cash_movements VALUES($id,$session,'Sale',$amount,$sale,$reason,$at)",ct,("$id",Guid.NewGuid()),("$session",Guid.Parse(sessionText)),("$amount",p.Amount),("$sale",saleId),("$reason",newMethod.ToString()),("$at",_clock.Now.ToString("O")));
        if(newMethod==PaymentMethod.StoreCredit)
        {
            await Exec(c,tx,"INSERT INTO credit_accounts VALUES($id,$customer,$sale,$amount,$amount,$at,$due,'Open',1,NULL)",ct,("$id",Guid.NewGuid()),("$customer",Guid.Parse(customer!)),("$sale",saleId),("$amount",p.Amount),("$at",_clock.Now.ToString("O")),("$due",_clock.Now.AddDays(30).ToString("O")));
        }
        await AddEvent(c,tx,saleId,operatorId,"PaymentChanged",reason,JsonSerializer.Serialize(new{from=p.Method.ToString(),to=newMethod.ToString(),amount=p.Amount}),ct);await tx.CommitAsync(ct);
    }

    public async Task<IReadOnlyList<CashMovementView>> CashHistoryAsync(Guid? sessionId=null,CancellationToken ct=default){var list=new List<CashMovementView>();await using var c=db.Open();await using var q=c.CreateCommand();q.CommandText="SELECT id,created_at,type,amount,reason,origin_id FROM cash_movements WHERE ($session IS NULL OR session_id=$session) ORDER BY created_at DESC LIMIT 1000";q.Parameters.AddWithValue("$session",(object?)sessionId?.ToString()??DBNull.Value);await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(Guid.Parse(r.GetString(0)),DateTimeOffset.Parse(r.GetString(1)),r.GetString(2),r.GetDecimal(3),r.GetString(4),r.IsDBNull(5)?null:Guid.Parse(r.GetString(5))));return list;}

    public async Task<Guid> ReopenLastCashAsync(Guid operatorId,string reason,CancellationToken ct=default){if(string.IsNullOrWhiteSpace(reason))throw new DomainException("Informe o motivo para reabrir o caixa.");await using var c=db.Open();await using var tx=(SqliteTransaction)await c.BeginTransactionAsync(ct);if(await ScalarLong(c,tx,"SELECT COUNT(*) FROM cash_sessions WHERE operator_id=$op AND closed_at IS NULL",("$op",operatorId),ct)>0)throw new DomainException("Já existe um caixa aberto. Feche-o antes de reabrir outro.");await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="SELECT id,closed_at,informed_total FROM cash_sessions WHERE operator_id=$op AND closed_at IS NOT NULL ORDER BY closed_at DESC LIMIT 1";q.Parameters.AddWithValue("$op",operatorId.ToString());await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new DomainException("Nenhum caixa fechado encontrado.");var id=Guid.Parse(r.GetString(0));var closed=r.GetString(1);var informed=r.IsDBNull(2)?null:(decimal?)r.GetDecimal(2);await r.DisposeAsync();await Exec(c,tx,"INSERT INTO cash_reopen_events VALUES($id,$session,$op,$reason,$at,$closed,$informed)",ct,("$id",Guid.NewGuid()),("$session",id),("$op",operatorId),("$reason",reason),("$at",_clock.Now.ToString("O")),("$closed",closed),("$informed",(object?)informed??DBNull.Value));await Exec(c,tx,"UPDATE cash_sessions SET closed_at=NULL,informed_total=NULL WHERE id=$id",ct,("$id",id));await tx.CommitAsync(ct);return id;}

    public async Task<Guid> SaveFiscalDraftAsync(Guid saleId,string? notes=null,CancellationToken ct=default){await using var c=db.Open();var exists=await ScalarText(c,null,"SELECT id FROM sales WHERE id=$id",("$id",saleId),ct);if(exists is null)throw new DomainException("Venda não encontrada.");var id=Guid.NewGuid();await using var q=c.CreateCommand();q.CommandText="INSERT INTO fiscal_drafts(id,sale_id,created_at,status,notes,updated_at) VALUES($id,$sale,$at,'Draft',$notes,$at) ON CONFLICT(sale_id) DO UPDATE SET notes=excluded.notes,updated_at=excluded.updated_at";q.Parameters.AddWithValue("$id",id.ToString());q.Parameters.AddWithValue("$sale",saleId.ToString());q.Parameters.AddWithValue("$at",_clock.Now.ToString("O"));q.Parameters.AddWithValue("$notes",(object?)notes??DBNull.Value);await q.ExecuteNonQueryAsync(ct);return id;}
    public async Task<IReadOnlyList<FiscalDraftView>> FiscalDraftsAsync(CancellationToken ct=default){var list=new List<FiscalDraftView>();await using var c=db.Open();await using var q=c.CreateCommand();q.CommandText="SELECT d.id,d.sale_id,s.number,d.created_at,d.status,s.total,COALESCE(cu.name,'CONSUMIDOR') FROM fiscal_drafts d JOIN sales s ON s.id=d.sale_id LEFT JOIN customers cu ON cu.id=s.customer_id ORDER BY d.created_at DESC";await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(Guid.Parse(r.GetString(0)),Guid.Parse(r.GetString(1)),r.GetInt64(2),DateTimeOffset.Parse(r.GetString(3)),r.GetString(4),r.GetDecimal(5),r.GetString(6)));return list;}
    public async Task MarkFiscalPendingAsync(Guid draftId,CancellationToken ct=default){await using var c=db.Open();await using var tx=(SqliteTransaction)await c.BeginTransactionAsync(ct);var sale=await ScalarText(c,tx,"SELECT sale_id FROM fiscal_drafts WHERE id=$id",("$id",draftId),ct)??throw new DomainException("Rascunho não encontrado.");await Exec(c,tx,"UPDATE fiscal_drafts SET status='Pending',updated_at=$at WHERE id=$id",ct,("$at",_clock.Now.ToString("O")),("$id",draftId));await Exec(c,tx,"UPDATE sales SET fiscal_status='Pending' WHERE id=$sale AND status='Completed'",ct,("$sale",Guid.Parse(sale)));await tx.CommitAsync(ct);}

    public async Task<QuoteView> SaveQuoteAsync(Cart cart,string? notes=null,int validDays=7,CancellationToken ct=default){if(cart.Items.Count==0)throw new DomainException("Carrinho vazio.");await using var c=db.Open();await using var tx=(SqliteTransaction)await c.BeginTransactionAsync(ct);var number=await ScalarLong(c,tx,"SELECT COALESCE(MAX(number),0)+1 FROM quotes",null,ct);var id=Guid.NewGuid();var at=_clock.Now;await Exec(c,tx,"INSERT INTO quotes(id,number,created_at,customer_id,discount,total,status,valid_until,notes) VALUES($id,$n,$at,$customer,$discount,$total,'Draft',$valid,$notes)",ct,("$id",id),("$n",number),("$at",at.ToString("O")),("$customer",(object?)cart.CustomerId?.ToString()??DBNull.Value),("$discount",cart.Discount),("$total",cart.Total),("$valid",at.AddDays(validDays).ToString("O")),("$notes",(object?)notes??DBNull.Value));foreach(var i in cart.Items)await Exec(c,tx,"INSERT INTO quote_items VALUES($id,$quote,$product,$code,$name,$q,$price,$sub)",ct,("$id",Guid.NewGuid()),("$quote",id),("$product",i.ProductId),("$code",i.Code),("$name",i.Name),("$q",i.Quantity),("$price",i.UnitPrice),("$sub",i.Subtotal));await tx.CommitAsync(ct);return new(id,number,at,"",cart.Total,"Draft",at.AddDays(validDays));}
    public async Task<IReadOnlyList<QuoteView>> QuotesAsync(CancellationToken ct=default){var list=new List<QuoteView>();await using var c=db.Open();await using var q=c.CreateCommand();q.CommandText="SELECT q.id,q.number,q.created_at,COALESCE(c.name,'CONSUMIDOR'),q.total,q.status,q.valid_until FROM quotes q LEFT JOIN customers c ON c.id=q.customer_id ORDER BY q.number DESC";await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(Guid.Parse(r.GetString(0)),r.GetInt64(1),DateTimeOffset.Parse(r.GetString(2)),r.GetString(3),r.GetDecimal(4),r.GetString(5),r.IsDBNull(6)?null:DateTimeOffset.Parse(r.GetString(6))));return list;}
    public async Task<Cart> LoadQuoteAsync(Guid quoteId,CancellationToken ct=default){var cart=new Cart();await using var c=db.Open();await using(var q=c.CreateCommand()){q.CommandText="SELECT customer_id,discount FROM quotes WHERE id=$id AND status='Draft'";q.Parameters.AddWithValue("$id",quoteId.ToString());await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new DomainException("Orçamento não encontrado ou já convertido.");cart.CustomerId=r.IsDBNull(0)?null:Guid.Parse(r.GetString(0));var discount=r.GetDecimal(1);await r.DisposeAsync();await using var qi=c.CreateCommand();qi.CommandText="SELECT product_id,code,name,quantity,unit_price FROM quote_items WHERE quote_id=$id ORDER BY rowid";qi.Parameters.AddWithValue("$id",quoteId.ToString());await using var ri=await qi.ExecuteReaderAsync(ct);while(await ri.ReadAsync(ct))cart.AddCustom(Guid.Parse(ri.GetString(0)),ri.GetString(1),ri.GetString(2),ri.GetDecimal(3),ri.GetDecimal(4));cart.SetDiscount(discount);}return cart;}
    public async Task MarkQuoteConvertedAsync(Guid quoteId,CancellationToken ct=default){await using var c=db.Open();await using var q=c.CreateCommand();q.CommandText="UPDATE quotes SET status='Converted' WHERE id=$id AND status='Draft'";q.Parameters.AddWithValue("$id",quoteId.ToString());if(await q.ExecuteNonQueryAsync(ct)!=1)throw new DomainException("Orçamento não encontrado ou já convertido.");}


    public async Task<IReadOnlyList<CartItem>> QuoteItemsAsync(Guid quoteId,CancellationToken ct=default){var list=new List<CartItem>();await using var c=db.Open();await using var q=c.CreateCommand();q.CommandText="SELECT product_id,code,name,quantity,unit_price FROM quote_items WHERE quote_id=$id ORDER BY rowid";q.Parameters.AddWithValue("$id",quoteId.ToString());await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(Guid.Parse(r.GetString(0)),r.GetString(1),r.GetString(2),r.GetDecimal(3),r.GetDecimal(4)));return list;}
    public async Task<string> SaleDeliveryTextAsync(Guid saleId,CancellationToken ct=default){await using var c=db.Open();string customer="CONSUMIDOR",address="",phone="";await using(var q=c.CreateCommand()){q.CommandText="SELECT COALESCE(c.name,'CONSUMIDOR'),COALESCE(c.phone,''),TRIM(COALESCE(c.address,'')||' '||COALESCE(c.number,'')||' '||COALESCE(c.complement,'')||' - '||COALESCE(c.district,'')||' - '||COALESCE(c.city,'')) FROM sales s LEFT JOIN customers c ON c.id=s.customer_id WHERE s.id=$id";q.Parameters.AddWithValue("$id",saleId.ToString());await using var r=await q.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct)){customer=r.GetString(0);phone=r.GetString(1);address=r.GetString(2);}}var items=new List<string>();await using(var q=c.CreateCommand()){q.CommandText="SELECT name,quantity FROM sale_items WHERE sale_id=$id ORDER BY rowid";q.Parameters.AddWithValue("$id",saleId.ToString());await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))items.Add($"{r.GetDecimal(1):0.###}x {r.GetString(0)}");}var sale=await new SqliteSaleRepository(db,_clock).GetAsync(saleId,ct);var total=sale?.Total??0m;return $"ONÇA PRODUTOS DE LIMPEZA - ENTREGA\nCliente: {customer}\nTelefone: {phone}\nEndereço: {address}\nItens: {string.Join(", ",items)}\nTotal: {total:C}";}

    private async Task AddEvent(SqliteConnection c,SqliteTransaction tx,Guid saleId,Guid op,string type,string reason,string? details,CancellationToken ct)=>await Exec(c,tx,"INSERT INTO sale_events VALUES($id,$sale,$type,$op,$reason,$details,$at)",ct,("$id",Guid.NewGuid()),("$sale",saleId),("$type",type),("$op",op),("$reason",reason),("$details",(object?)details??DBNull.Value),("$at",_clock.Now.ToString("O")));
    private static async Task<int> Exec(SqliteConnection c,SqliteTransaction tx,string sql,CancellationToken ct,params(string,object)[] ps){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText=sql;foreach(var p in ps)q.Parameters.AddWithValue(p.Item1,p.Item2 is Guid id?id.ToString():p.Item2);return await q.ExecuteNonQueryAsync(ct);}
    private static async Task<string?> ScalarText(SqliteConnection c,SqliteTransaction? tx,string sql,(string,object)? p,CancellationToken ct){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText=sql;if(p is { } x)q.Parameters.AddWithValue(x.Item1,x.Item2 is Guid id?id.ToString():x.Item2);var v=await q.ExecuteScalarAsync(ct);return v is null||v is DBNull?null:Convert.ToString(v);}
    private static async Task<long> ScalarLong(SqliteConnection c,SqliteTransaction tx,string sql,(string,object)? p,CancellationToken ct){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText=sql;if(p is { } x)q.Parameters.AddWithValue(x.Item1,x.Item2 is Guid id?id.ToString():x.Item2);return Convert.ToInt64(await q.ExecuteScalarAsync(ct));}
}
